---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hedgedoc-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        AWS_ACCESS_KEY_ID: "{{ .OUTLINE__S3_ACCESS_KEY_ID  }}"
        AWS_SECRET_ACCESS_KEY: "{{ .OUTLINE__S3_SECRET_ACCESS_KEY }}"
        SECRET_KEY: "{{ .OUTLINE__SECRET_KEY }}"
        UTILS_SECRET: "{{ .OUTLINE__UTILS_SECRET }}"
        DATABASE_URL: "postgres://{{ .OUTLINE__POSTGRES_USER }}:{{ .OUTLINE__POSTGRES_PASS }}@postgres16-rw.database.svc.cluster.local:5432/outline"
        # Authentik
        OIDC_CLIENT_ID: "{{ .OUTLINE__OAUTH_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .OUTLINE__OAUTH_CLIENT_SECRET }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: "{{ .OUTLINE__POSTGRES_DBNAME }}"
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .OUTLINE__POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .OUTLINE__POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  data:
    - secretKey: OUTLINE__SECRET_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 8298fbc6-4853-46c9-9844-e6daf62310dd
        property: secret_key
    - secretKey: OUTLINE__UTILS_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 8298fbc6-4853-46c9-9844-e6daf62310dd
        property: utils_secret

    - secretKey: OUTLINE__S3_ACCESS_KEY_ID
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 8298fbc6-4853-46c9-9844-e6daf62310dd
        property: s3_access_key_id
    - secretKey: OUTLINE__S3_SECRET_ACCESS_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 8298fbc6-4853-46c9-9844-e6daf62310dd
        property: s3_secret_access_key

    - secretKey: OUTLINE__POSTGRES_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 8298fbc6-4853-46c9-9844-e6daf62310dd
        property: pg_user
    - secretKey: OUTLINE__POSTGRES_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 8298fbc6-4853-46c9-9844-e6daf62310dd
        property: pg_password

    - secretKey: OUTLINE__OAUTH_CLIENT_ID
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 8298fbc6-4853-46c9-9844-e6daf62310dd
        property: oauth_client_id
    - secretKey: OUTLINE__OAUTH_CLIENT_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 8298fbc6-4853-46c9-9844-e6daf62310dd
        property: oauth_client_secret

    - secretKey: POSTGRES_SUPER_USER
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: username
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: password
