---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cross-seed-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        PROWLARR__API_KEY: "{{ .PROWLARR__API_KEY }}"
  data:
    - secretKey: PROWLARR__API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 43e68fd7-3987-4d16-95ea-64505d0748c5
        property: token
