---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cross-seed
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: qbittorrent
      namespace: downloads
  values:
    controllers:
      main:
        annotations:
          secret.reloader.stakater.com/reload: cross-seed-secret
        containers:
          main:
            image:
              repository: ghcr.io/cross-seed/cross-seed
              tag: 5.9.1@sha256:43362a39bb0ec825c046bbc255c41d557f98c0835dd1d6146eb93e03d36a98b9
            env:
              TZ: "${TIMEZONE}"
              CROSSSEED_PORT: &port 80
            envFrom:
              - secretRef:
                  name: cross-seed-secret
            args:
              - daemon
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 512Mi
        pod:
          metadata:
            labels:
              app: cross-seed
          #nodeSelector:
          #  app.kubernetes.io/instance: qbittorrent
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                    - qbittorrent
                topologyKey: "kubernetes.io/hostname"
          #      #matchLabelKeys:
          #      #- pod-template-hash
          securityContext:
            runAsUser: 1031
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups: [10000]
    service:
      main:
        ports:
          http:
            port: *port
    persistence:
      config:
        enabled: true
        existingClaim: qbittorrent
        globalMounts:
          - path: /config
      config-file:
        type: configMap
        name: cross-seed-configmap
        globalMounts:
          - path: /config/config.js
            subPath: config.js
            readOnly: true
      downloads:
        type: nfs
        server: mega.home.ld
        path: /volume1/Media
        globalMounts:
          - path: /media
