---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wordpress-db-secret
  namespace: selfhosted
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        username: &dbUser "{{ .WORDPRESS__DB_USER }}"
        password: &dbPass "{{ .WORDPRESS__DB_PASS }}"
  data:
    - secretKey: WORDPRESS__DB_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: f465cb04-cf5c-4597-ba41-c4b5fbd7a368
        property: mariadb_user
    - secretKey: WORDPRESS__DB_PASS
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: f465cb04-cf5c-4597-ba41-c4b5fbd7a368
        property: mariadb_password
