---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: paperless-gotenberg
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          main:
            image:
              repository: thecodingmachine/gotenberg
              tag: 8.1.0
            env:
              - { name: DISABLE_GOOGLE_CHROME, value: "1" }
            resources:
              requests:
                cpu: 11m
                memory: 512Mi
              limits:
                memory: 1800M
        pod:
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
            fsGroup: 1001
            #fsGroup: 65542
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups:
              - 65542

    service:
      main:
        ports:
          http:
            port: 3000

    ingress:
      main:
        enabled: true
        className: internal
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    #persistence:
    #  library:
    #    enabled: true
    #    existingClaim: paperless-nfs
    #    globalMounts:
    #      - path: /library
      #data:
      #  enabled: true
      #  globalMounts:
      #    - path: /data/local
      #  existingClaim: paperless
      #library:
      #  type: nfs
      #  server: mega.home.ld
      #  path: /volume1/Media/paperless
      #  globalMounts:
      #    - path: /library
