---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hedgedoc-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        REDIS_PASSWORD: "{{ .REDIS__PASSWORD }}"
  data:
    - secretKey: REDIS__PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 1c8993b6-04c0-418e-bafc-d512ef33e4b2
        property: password
