---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
  - ./external-secret.yaml
  - ./pvc.yaml
  - ./configmap.yaml
  - ./helmrelease.yaml
  - ./gatus.yaml
