---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: rook-ceph-cluster
      version: v1.13.7
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: snapshot-controller
      namespace: kube-system
  values:
    monitoring:
      enabled: true
      createPrometheusRules: true
      externalMgrEndpoints:
        - ip: "172.17.0.11"
        - ip: "172.17.0.12"
        - ip: "172.17.0.13"
      externalMgrPrometheusPort: 9283
    ingress:
      dashboard:
        ingressClassName: internal
        host:
          name: &host rook.${SECRET_DOMAIN}
          path: /
        tls:
          - hosts:
              - *host
    toolbox:
      enabled: true
    cephClusterSpec:
      external:
        enable: true
      network:
        connections:
          encryption:
            enabled: false
          compression:
            enabled: false
          requireMsgr2: false
      dataDirHostPath: /var/lib/rook
      cephVersion:
        image: quay.io/ceph/ceph:v18.2.1
      crashCollector:
        disable: true
      healthCheck:
        daemonHealth:
          mon:
            disabled: false
            interval: 45s
      dashboard:
        enabled: true
        urlPrefix: /
        ssl: false
    cephBlockPools: {}
    #  - name: ceph-blockpool
    #    spec:
    #
    #    storageClass:
    #      enabled: true
    #      name: ceph-block
    #      isDefault: true
    #      reclaimPolicy: Delete
    #      allowVolumeExpansion: true
    #      parameters:
    #        imageFormat: "2"
    #        imageFeatures: layering,fast-diff,object-map,deep-flatten,exclusive-lock
    #        csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
    #        csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
    #        csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
    #        csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
    #        csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
    #        csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
    #        csi.storage.k8s.io/fstype: ext4
    cephBlockPoolsVolumeSnapshotClass:
      enabled: true
      name: csi-ceph-blockpool
      isDefault: false
      deletionPolicy: Delete
    cephFileSystems: {}
    #  - name: ceph-filesystem
    #    storageClass:
    #      enabled: true
    #      isDefault: false
    #      name: ceph-filesystem
    #      pool: cephfs_data
    #      reclaimPolicy: Delete
    #      allowVolumeExpansion: true
    #      parameters:
    #        csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
    #        csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
    #        csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
    #        csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
    #        csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
    #        csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
    #        csi.storage.k8s.io/fstype: ext4
    cephFileSystemVolumeSnapshotClass:
      enabled: true
      name: csi-ceph-filesystem
      isDefault: false
      deletionPolicy: Delete
    cephObjectStores: {}
    #  - name: ceph-objectstore
    #    storageClass:
    #      enabled: true
    #      name: ceph-bucket
    #      reclaimPolicy: Delete
    #      parameters:
    #        region: ca-east-1
