apiVersion: v1
data:
    admin-secret: ENC[AES256_GCM,data:B3rUstoSdXPL7ybHwKMlLA==,iv:a112vrMEcZLmE20jtv2PUZe/aqP4R2trSzZIMLFvPQI=,tag:su4VDrk7EbI7afGg0ccXFQ==,type:str]
    ceph-secret: ENC[AES256_GCM,data:GRMlQByQlPryKFMld3Nsfm9BrR1clnDbfYw2zZjDgd1OqvGVEezcjI1kHOaCaDMPXumr/nkcmVE=,iv:o9LfDaNGUOnwDBWGMqVYwBXxiPqAJrj6Hlk5IMp7ptA=,tag:1dzi0NVC90sToM3f54wvWg==,type:str]
    ceph-username: ENC[AES256_GCM,data:t65ra5OGINygRrYZZjaVfh8JCXZXJ5fhL10XGQ==,iv:ti9zoOswD0LNfMhUVqBu9tAe43QDdiLsXXMVMCUPLXo=,tag:XWlv5lvlKux2IzrREidg2A==,type:str]
    cluster-name: ENC[AES256_GCM,data:uImxRPAQfjm8+FT3,iv:+hfZdm/g56vKsV7TKOSIV6WRcStUPH8eCiz8qRkqQ+k=,tag:WJ3SRBerczRCQpPhSyN6GQ==,type:str]
    fsid: ENC[AES256_GCM,data:Qx4fZfMguRz6ui0LsZIqC3nQBp544WRdBtPIsow/mDhcFOQAEYqePlCt4EHdqO+C,iv:Chz6L4EU5br+Mswjg58dT+r2Njp4bu8WBZB99PlfrY8=,tag:01RTo2S1NLlGiZn91ejOSQ==,type:str]
    mon-secret: ENC[AES256_GCM,data:LHI2CDvxS688OsKc2vkCFJChhajRrURVpOiBEtDozot3vT+0MHhLsTY/3rkXbmmQ,iv:nWstgXdqo2jw2/jXz3CvVHq8g4AWX2EzoZ0c4Sj2QTM=,tag:zoPmBBlQIhgzu7dBoZXQpA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: rook-ceph-mon
    namespace: rook-ceph
type: kubernetes.io/rook
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age126422qm0mrq0tpmm0rjcacjznz8ggcf2map6yrz3y944e8x4tansxe73l5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YzVGSDdpczJYVjZQTFo2
            eTJMMElLOGtKWmQvZzNEMWkyV2JkTzllVHpjCnp0L0c4bjVOUkkxeWFDcldhdnFJ
            Tkt3cmNBWG5uQUV5cUpGd1MzQXNXNG8KLS0tIHgzRlI1bERwa2Q4TENvb08yWXp4
            V0JYaFovckZwWGlYNGFVR2RVVVRTcTQKycbR38VrM0JiNPpUBvVPhs8NsGWewLST
            o2tURWbjWMhCoXHjrfNavXs8cok9iFVEgkMXgLv/E+IJif5H+p+TiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-21T06:08:21Z"
    mac: ENC[AES256_GCM,data:p0m9YsKndDGOHoNrKWEYXNEtTWYvPWH0pnWzG8GL0zE42Zrxox+ytNUJmSr+b86iIwTc4tTiKESEdp6+CRqgQr8T92R6aBUpiSG7tASAkB2vExF1aJw+saP/al6bhUaX/jr5NiABh4VEmRhxiLbkDJ8hdGoTXl+LduvbEVho13M=,iv:T/S7YbgpNzsH5uOCfgVPzG6z7T/yMICQlIqhiN02OlE=,tag:INulywddiNbSIStgZmOlFg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
data:
    data: ENC[AES256_GCM,data:CT2QWCiLPQD1h03So2+zDej63GamkXbU+86BhKVDWICQAs1xs/2Ui1yZZhHJ0IOuZDMQSfwP5JdVqYg=,iv:vuKy7bF0QGymtejexm1DQx13bqs4XZqZw+Yr2EJ+IuU=,tag:U/wH0cdlKL1UCJ6Ilz0hlQ==,type:str]
    mapping: {}
    maxMonId: ENC[AES256_GCM,data:ow==,iv:AKQfXonG29A9ce1R5uUKs7QPHIkHACKGouhy+6MIdME=,tag:b9det4SmaK63mUtSxVOjYQ==,type:int]
kind: ConfigMap
metadata:
    creationTimestamp: null
    name: rook-ceph-mon-endpoints
    namespace: rook-ceph
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age126422qm0mrq0tpmm0rjcacjznz8ggcf2map6yrz3y944e8x4tansxe73l5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YzVGSDdpczJYVjZQTFo2
            eTJMMElLOGtKWmQvZzNEMWkyV2JkTzllVHpjCnp0L0c4bjVOUkkxeWFDcldhdnFJ
            Tkt3cmNBWG5uQUV5cUpGd1MzQXNXNG8KLS0tIHgzRlI1bERwa2Q4TENvb08yWXp4
            V0JYaFovckZwWGlYNGFVR2RVVVRTcTQKycbR38VrM0JiNPpUBvVPhs8NsGWewLST
            o2tURWbjWMhCoXHjrfNavXs8cok9iFVEgkMXgLv/E+IJif5H+p+TiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-21T06:08:21Z"
    mac: ENC[AES256_GCM,data:p0m9YsKndDGOHoNrKWEYXNEtTWYvPWH0pnWzG8GL0zE42Zrxox+ytNUJmSr+b86iIwTc4tTiKESEdp6+CRqgQr8T92R6aBUpiSG7tASAkB2vExF1aJw+saP/al6bhUaX/jr5NiABh4VEmRhxiLbkDJ8hdGoTXl+LduvbEVho13M=,iv:T/S7YbgpNzsH5uOCfgVPzG6z7T/yMICQlIqhiN02OlE=,tag:INulywddiNbSIStgZmOlFg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
data:
    userID: ENC[AES256_GCM,data:eKhNszWDYdBw7yRtmN0v0w==,iv:Rt31sPnaHj+0s0A0nI+gTHaZn5XfXOh8MTJBqDJxBA4=,tag:dB982y/mvmsWRDry7s1ong==,type:str]
    userKey: ENC[AES256_GCM,data:jtP8FAs5kUOJcFAxJw+ud+680Wqh6BbH1xivwieQyVmM2TO+YvvIROrwJSBQN/sIRESJazj/LXI=,iv:xxj4MIdr3IQL2MiGi8EuVcebWIx6LupA+X0N0oqVVo4=,tag:Gc3Xq7CoWgQA+qeYTPUAPg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: rook-csi-rbd-node
    namespace: rook-ceph
type: kubernetes.io/rook
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age126422qm0mrq0tpmm0rjcacjznz8ggcf2map6yrz3y944e8x4tansxe73l5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YzVGSDdpczJYVjZQTFo2
            eTJMMElLOGtKWmQvZzNEMWkyV2JkTzllVHpjCnp0L0c4bjVOUkkxeWFDcldhdnFJ
            Tkt3cmNBWG5uQUV5cUpGd1MzQXNXNG8KLS0tIHgzRlI1bERwa2Q4TENvb08yWXp4
            V0JYaFovckZwWGlYNGFVR2RVVVRTcTQKycbR38VrM0JiNPpUBvVPhs8NsGWewLST
            o2tURWbjWMhCoXHjrfNavXs8cok9iFVEgkMXgLv/E+IJif5H+p+TiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-21T06:08:21Z"
    mac: ENC[AES256_GCM,data:p0m9YsKndDGOHoNrKWEYXNEtTWYvPWH0pnWzG8GL0zE42Zrxox+ytNUJmSr+b86iIwTc4tTiKESEdp6+CRqgQr8T92R6aBUpiSG7tASAkB2vExF1aJw+saP/al6bhUaX/jr5NiABh4VEmRhxiLbkDJ8hdGoTXl+LduvbEVho13M=,iv:T/S7YbgpNzsH5uOCfgVPzG6z7T/yMICQlIqhiN02OlE=,tag:INulywddiNbSIStgZmOlFg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
data:
    userID: ENC[AES256_GCM,data:nsav3Sc60Eii0XDvNpx8YehqxPuzhywZqMCIGg==,iv:Fuq4JpgRdp0HRb3w1MxxyEJOaO40Y0DlF9eySs9QX/0=,tag:9yC59VJvxhQRv/ltEJKDhA==,type:str]
    userKey: ENC[AES256_GCM,data:OSa5h/VTUonviUeyYBfIbzmsU1jqygsLw6MKUxSn9KITo6DUKBkCMsiguh5E1N3854OUU5vz3Vo=,iv:J4MVwVsz6fDwgnrDn98tjPZiw2XzfrfbLgzBHZHRULU=,tag:gCHsiVld31H1y3a4UMTo4Q==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: rook-csi-rbd-provisioner
    namespace: rook-ceph
type: kubernetes.io/rook
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age126422qm0mrq0tpmm0rjcacjznz8ggcf2map6yrz3y944e8x4tansxe73l5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YzVGSDdpczJYVjZQTFo2
            eTJMMElLOGtKWmQvZzNEMWkyV2JkTzllVHpjCnp0L0c4bjVOUkkxeWFDcldhdnFJ
            Tkt3cmNBWG5uQUV5cUpGd1MzQXNXNG8KLS0tIHgzRlI1bERwa2Q4TENvb08yWXp4
            V0JYaFovckZwWGlYNGFVR2RVVVRTcTQKycbR38VrM0JiNPpUBvVPhs8NsGWewLST
            o2tURWbjWMhCoXHjrfNavXs8cok9iFVEgkMXgLv/E+IJif5H+p+TiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-21T06:08:21Z"
    mac: ENC[AES256_GCM,data:p0m9YsKndDGOHoNrKWEYXNEtTWYvPWH0pnWzG8GL0zE42Zrxox+ytNUJmSr+b86iIwTc4tTiKESEdp6+CRqgQr8T92R6aBUpiSG7tASAkB2vExF1aJw+saP/al6bhUaX/jr5NiABh4VEmRhxiLbkDJ8hdGoTXl+LduvbEVho13M=,iv:T/S7YbgpNzsH5uOCfgVPzG6z7T/yMICQlIqhiN02OlE=,tag:INulywddiNbSIStgZmOlFg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
data:
    adminID: ENC[AES256_GCM,data:fs8wAy9Ex6DcNxze6U7vp4mZxq4=,iv:nfL5sUux8E9Tq7soOOA/c1ghUeGkduHwDleCJDd5lVc=,tag:QakfYbNxqOYS/xrV1XRtyw==,type:str]
    adminKey: ENC[AES256_GCM,data:NlZ/TxZ9/zHtwJe0us8jEHMYSAXs+Gpi+Jn606TGBRtLXkPdz24w16ON/BQ2WpwaxGoEj3fVMqw=,iv:0PXTdVQd2lNpYfwymUUcZhXrN6T5hbN5pB3Jyifb7QE=,tag:NK4VvUy0dWZuDqlL0d6oyg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: rook-csi-cephfs-node
    namespace: rook-ceph
type: kubernetes.io/rook
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age126422qm0mrq0tpmm0rjcacjznz8ggcf2map6yrz3y944e8x4tansxe73l5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YzVGSDdpczJYVjZQTFo2
            eTJMMElLOGtKWmQvZzNEMWkyV2JkTzllVHpjCnp0L0c4bjVOUkkxeWFDcldhdnFJ
            Tkt3cmNBWG5uQUV5cUpGd1MzQXNXNG8KLS0tIHgzRlI1bERwa2Q4TENvb08yWXp4
            V0JYaFovckZwWGlYNGFVR2RVVVRTcTQKycbR38VrM0JiNPpUBvVPhs8NsGWewLST
            o2tURWbjWMhCoXHjrfNavXs8cok9iFVEgkMXgLv/E+IJif5H+p+TiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-21T06:08:21Z"
    mac: ENC[AES256_GCM,data:p0m9YsKndDGOHoNrKWEYXNEtTWYvPWH0pnWzG8GL0zE42Zrxox+ytNUJmSr+b86iIwTc4tTiKESEdp6+CRqgQr8T92R6aBUpiSG7tASAkB2vExF1aJw+saP/al6bhUaX/jr5NiABh4VEmRhxiLbkDJ8hdGoTXl+LduvbEVho13M=,iv:T/S7YbgpNzsH5uOCfgVPzG6z7T/yMICQlIqhiN02OlE=,tag:INulywddiNbSIStgZmOlFg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
data:
    adminID: ENC[AES256_GCM,data:dWUAQRzyj58II0T6Q5FvWs9ul0A2uDx64fKkSgXC1q0=,iv:egZJIlG/3jTwzMC6twMsYCch0rbXWy1HXPRGvg52Rmo=,tag:pDY9AXX6VvNXfagZ1OtJgA==,type:str]
    adminKey: ENC[AES256_GCM,data:Ls0Vuz3kvpbFFb8+G4tzmLVA21EvVMpK1297nx8BMKeJtwrjSAcZT8dGaX6M4NriDV9qSXYLmVU=,iv:TBJUao/U1w9IYTrUHGlLNsNYdNl48U/NMdoPRiG2p/E=,tag:yr56Gft/QILQRld9D1om8g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: rook-csi-cephfs-provisioner
    namespace: rook-ceph
type: kubernetes.io/rook
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age126422qm0mrq0tpmm0rjcacjznz8ggcf2map6yrz3y944e8x4tansxe73l5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YzVGSDdpczJYVjZQTFo2
            eTJMMElLOGtKWmQvZzNEMWkyV2JkTzllVHpjCnp0L0c4bjVOUkkxeWFDcldhdnFJ
            Tkt3cmNBWG5uQUV5cUpGd1MzQXNXNG8KLS0tIHgzRlI1bERwa2Q4TENvb08yWXp4
            V0JYaFovckZwWGlYNGFVR2RVVVRTcTQKycbR38VrM0JiNPpUBvVPhs8NsGWewLST
            o2tURWbjWMhCoXHjrfNavXs8cok9iFVEgkMXgLv/E+IJif5H+p+TiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-21T06:08:21Z"
    mac: ENC[AES256_GCM,data:p0m9YsKndDGOHoNrKWEYXNEtTWYvPWH0pnWzG8GL0zE42Zrxox+ytNUJmSr+b86iIwTc4tTiKESEdp6+CRqgQr8T92R6aBUpiSG7tASAkB2vExF1aJw+saP/al6bhUaX/jr5NiABh4VEmRhxiLbkDJ8hdGoTXl+LduvbEVho13M=,iv:T/S7YbgpNzsH5uOCfgVPzG6z7T/yMICQlIqhiN02OlE=,tag:INulywddiNbSIStgZmOlFg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
data:
    accessKey: ENC[AES256_GCM,data:dKHs3riye633ffARguSN7TN52YdAJ2tjvT32Zw==,iv:bcNWFMkvlXKYHMs/l6y1+KwR0MjhvaFlgdUl1PTaX+c=,tag:61i41y6kbyoYSs0rsurBpA==,type:str]
    secretKey: ENC[AES256_GCM,data:D2JoImfALfCu5pJ3En7ptSEcL99TEu2S4283O5rpHHuKTGKcmZNt3weQB5XW+hmILo108dK/1AI=,iv:GjDYU2O4i2pXXsL8tnHP1Yx9vr8VReLa0KaL2Mbj2UA=,tag:14NKc8MQSCgHfxpSFdp5RQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: rgw-admin-ops-user
    namespace: rook-ceph
type: kubernetes.io/rook
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age126422qm0mrq0tpmm0rjcacjznz8ggcf2map6yrz3y944e8x4tansxe73l5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YzVGSDdpczJYVjZQTFo2
            eTJMMElLOGtKWmQvZzNEMWkyV2JkTzllVHpjCnp0L0c4bjVOUkkxeWFDcldhdnFJ
            Tkt3cmNBWG5uQUV5cUpGd1MzQXNXNG8KLS0tIHgzRlI1bERwa2Q4TENvb08yWXp4
            V0JYaFovckZwWGlYNGFVR2RVVVRTcTQKycbR38VrM0JiNPpUBvVPhs8NsGWewLST
            o2tURWbjWMhCoXHjrfNavXs8cok9iFVEgkMXgLv/E+IJif5H+p+TiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-21T06:08:21Z"
    mac: ENC[AES256_GCM,data:p0m9YsKndDGOHoNrKWEYXNEtTWYvPWH0pnWzG8GL0zE42Zrxox+ytNUJmSr+b86iIwTc4tTiKESEdp6+CRqgQr8T92R6aBUpiSG7tASAkB2vExF1aJw+saP/al6bhUaX/jr5NiABh4VEmRhxiLbkDJ8hdGoTXl+LduvbEVho13M=,iv:T/S7YbgpNzsH5uOCfgVPzG6z7T/yMICQlIqhiN02OlE=,tag:INulywddiNbSIStgZmOlFg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
