---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-cilium
  namespace: flux-system
  labels:
    kustomization.flux.home.arpa/name: "cilium"
    kustomization.flux.home.arpa/helmpatches: "false"
spec:
  path: ./kubernetes/apps/kube-system/cilium/app
  prune: false # never should be deleted
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
#---
#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: cluster-apps-cilium-config
#  namespace: flux-system
#  labels:
#    kustomization.flux.home.arpa/name: "cilium"
#    kustomization.flux.home.arpa/helmpatches: "false"
#spec:
#  path: ./kubernetes/apps/kube-system/cilium/config
#  dependsOn:
#    - name: cluster-apps-cilium
#  prune: false # never should be deleted
#  sourceRef:
#    kind: GitRepository
#    name: home-kubernetes
#  wait: false
#  interval: 30m
#  retryInterval: 1m
#  timeout: 5m
