---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        ## Non Cluster resources
        HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: "{{ .cloudflare_accountid }}"
        HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: "{{ .cloudflare_tunnelid }}"
        HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: "{{ .cloudflare_key }}"
        HOMEPAGE_VAR_DOCKER_PLEX_TOKEN: "{{ .plex_docker_token }}"
        HOMEPAGE_VAR_DOCKER_TAUTULLI_TOKEN: "{{ .tautulli_docker_token }}"
        HOMEPAGE_VAR_PIHOLE_TOKEN: "{{ .pihole_token }}"
        HOMEPAGE_VAR_NEXTDNS_ID: "{{ .nextdns_id }}"
        HOMEPAGE_VAR_NEXTDNS_API: "{{ .nextdns_api }}"
        HOMEPAGE_VAR_PORTAINER_TOKEN: "{{ .portainer_token }}"
        HOMEPAGE_VAR_UNIFI_USERNAME: "{{ .unifi_user }}"
        HOMEPAGE_VAR_UNIFI_PASSWORD: "{{ .unifi_pass }}"
        ## Default
        HOMEPAGE_VAR_HASS_TOKEN: "{{ .hass_token }}"
        ## Downloads
        HOMEPAGE_VAR_BAZARR_TOKEN: "{{ .bazarr_token }}"
        HOMEPAGE_VAR_KAPOWARR_TOKEN: "{{ .kapowarr_token }}"
        HOMEPAGE_VAR_MYLAR_TOKEN: "{{ .mylar_token }}"
        HOMEPAGE_VAR_PROWLARR_TOKEN: "{{ .prowlarr_token }}"
        HOMEPAGE_VAR_QBITTORRENT_USERNAME: "{{ .qbittorrent_username }}"
        HOMEPAGE_VAR_QBITTORRENT_PASSWORD: "{{ .qbittorrent_password }}"
        HOMEPAGE_VAR_RADARR_TOKEN: "{{ .radarr_token }}"
        HOMEPAGE_VAR_READARR_TOKEN: "{{ .readarr_token }}"
        HOMEPAGE_VAR_SABNZBD_TOKEN: "{{ .sabnzbd_token }}"
        HOMEPAGE_VAR_SONARR_TOKEN: "{{ .sonarr_token }}"
        ## Media
        HOMEPAGE_VAR_OVERSEERR_TOKEN: "{{ .overseerr_token }}"
        HOMEPAGE_VAR_PLEX_TOKEN: "{{ .plex_token }}"
        HOMEPAGE_VAR_TAUTULLI_TOKEN: "{{ .tautulli_token }}"
        HOMEPAGE_VAR_KAVITA_USERNAME: "{{ .kavita_username }}"
        HOMEPAGE_VAR_KAVITA_PASSWORD: "{{ .kavita_password }}"
        ## Monitoring
        HOMEPAGE_VAR_GRAFANA_USERNAME: "{{ .grafana_username }}"
        HOMEPAGE_VAR_GRAFANA_PASSWORD: "{{ .grafana_password }}"
        ## Security
        HOMEPAGE_VAR_AUTHENTIK_TOKEN: "{{ .authentik_token }}"
  data:
    ## Non Cluster
    - secretKey: cloudflare_accountid
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 136c1200-904a-4e3c-bd02-ac6e00f706e3
        property: account_id
    - secretKey: cloudflare_tunnelid
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 136c1200-904a-4e3c-bd02-ac6e00f706e3
        property: tunnel_id
    - secretKey: cloudflare_key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 136c1200-904a-4e3c-bd02-ac6e00f706e3
        property: api_token
    - secretKey: plex_docker_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 5f4a73e9-dbaa-47bf-a5f2-ac6e00f706e3
        property: token
    - secretKey: tautulli_docker_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 9be660f2-f018-41fa-91db-afd500dfc709
        property: docker_token
    - secretKey: pihole_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 27fe4940-03ac-4718-815a-b0200144dda7
        property: token
    - secretKey: nextdns_id
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: dc5c6a13-709f-455b-b2af-b04200dad40d
        property: ID
    - secretKey: nextdns_api
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: dc5c6a13-709f-455b-b2af-b04200dad40d
        property: API
    - secretKey: portainer_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 7b792cef-9d6d-48f1-9fe0-acfa010ac442
        property: token
    - secretKey: unifi_user
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 02cfb975-77dc-46fb-96b2-afd60023b1a1
        property: username
    - secretKey: unifi_pass
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 02cfb975-77dc-46fb-96b2-afd60023b1a1
        property: password
    ## Default
    - secretKey: hass_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: b3582fd9-4e36-4adf-83b3-adec011a84fd
        property: token
    ## Downloads
    - secretKey: bazarr_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: dd1001b2-9c2e-409b-ab81-afd500d9ba6a
        property: token
    - secretKey: kapowarr_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 01806b71-fed2-4214-a80f-b04500fc17c5
        property: token
    - secretKey: mylar_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: cfe083fb-6377-49fa-ad0f-b02001445f7c
        property: token
    - secretKey: prowlarr_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 7fa0147f-6ab6-44b1-9ba2-af8f01172e77
        property: token
    - secretKey: qbittorrent_username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 7bda7d2b-e9d8-4699-b43a-afc50017aab5
        property: username
    - secretKey: qbittorrent_password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 7bda7d2b-e9d8-4699-b43a-afc50017aab5
        property: password
    - secretKey: radarr_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 33a5fd65-38fb-40d6-b4a6-ac6e00f706e3
        property: token
    - secretKey: readarr_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: f8621570-ad69-40ef-8315-afd500df25b3
        property: token
    - secretKey: sabnzbd_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 11eae6bf-761a-433f-ad9a-ac6e00f706e3
        property: api_token
    - secretKey: sonarr_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: f131edf2-177b-4284-b606-ac6e00f706e3
        property: token
    ## Media
    - secretKey: overseerr_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d6c7ed5d-dc6c-4a61-8df5-afd500e1d0ef
        property: token
    - secretKey: plex_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 5f4a73e9-dbaa-47bf-a5f2-ac6e00f706e3
        property: token
    - secretKey: tautulli_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 9be660f2-f018-41fa-91db-afd500dfc709
        property: k8s_token
    - secretKey: kavita_username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 675ec17c-ab29-48fe-a7e8-b0050110a1a7
        property: username
    - secretKey: kavita_password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 675ec17c-ab29-48fe-a7e8-b0050110a1a7
        property: password
    ## Monitoring
    - secretKey: grafana_username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b36a66be-7898-4003-902a-afc701166ed9
        property: username
    - secretKey: grafana_password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b36a66be-7898-4003-902a-afc701166ed9
        property: password
    ## Security
    - secretKey: authentik_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 3ff34fd7-ec65-436c-865c-afcf0104ce37
        property: token
