---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rainloop-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        ROUNDCUBEMAIL_DB_TYPE: pgsql
        ROUNDCUBEMAIL_DB_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        ROUNDCUBEMAIL_DB_PORT: "5432"
        ROUNDCUBEMAIL_DB_USER: &dbUser "{{ .ROUNDCUBE__POSTGRES_USER }}"
        ROUNDCUBEMAIL_DB_PASSWORD: &dbPass "{{ .ROUNDCUBE_POSTGRES_PASSWORD }}"
        ROUNDCUBEMAIL_DB_NAME: &dbName roundcube
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  data:
    - secretKey: ROUNDCUBE__POSTGRES_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 7a8ad09f-77af-49b2-8d69-b581ca0554e5
        property: pg_user
    - secretKey: ROUNDCUBE__POSTGRES_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 7a8ad09f-77af-49b2-8d69-b581ca0554e5
        property: pg_password

    - secretKey: POSTGRES_SUPER_USER
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: username
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: password
