---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: roundcube
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      main:
        strategy: RollingUpdate

        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
              pullPolicy: IfNotPresent
            envFrom: &envFrom
              - secretRef:
                  name: roundcube-secret

        containers:
          main:
            image:
              repository: roundcube/roundcubemail
              tag: 1.5.6-apache
            env:
              TZ: "${TIMEZONE}"
              ROUNDCUBEMAIL_DEFAULT_HOST: ssl://${MAIL_PROD_IMAP}
              ROUNDCUBEMAIL_DEFAULT_PORT: 993
              ROUNDCUBEMAIL_SMTP_SERVER: tls://${MAIL_PROD_SMTP}
              ROUNDCUBEMAIL_SMTP_PORT: 587
              ROUNDCUBEMAIL_PLUGINS: "archive,managesieve,zipdownload"
              ROUNDCUBEMAIL_SKIN: "elastic"
              ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE: "128m"
            envFrom: *envFrom
            resources:
              requests:
                cpu: 12m
                memory: 64M
              limits:
                memory: 512M

    service:
      main:
        ports:
          http:
            port: 80

    ingress:
      main:
        enabled: true
        className: "external"
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
        hosts:
          - host: &host "webmail.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      data:
        enabled: true
        existingClaim: roundcube
        globalMounts:
          - path: /var/roundcube/config
