---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ../../../../templates/gatus/guarded
  - ../../../../templates/volsync
configMapGenerator:
  - name: qbittorrent-scripts
    files:
      - ./config/completed.sh
  - name: cross-seed-configmap
    files:
      - config.js=./resources/config.js
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
