---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: autobrr-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        AUTOBRR__DATABASE_TYPE: postgres
        AUTOBRR__POSTGRES_DATABASE: &dbName autobrr
        AUTOBRR__POSTGRES_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        AUTOBRR__POSTGRES_USER: &dbUser "{{ .AUTOBRR_POSTGRES_USER }}"
        AUTOBRR__POSTGRES_PASS: &dbPass "{{ .AUTOBRR_POSTGRES_PASS }}"
        AUTOBRR__POSTGRES_PORT: "5432"
        AUTOBRR__SESSION_SECRET: "{{ .AUTOBRR_SESSION_SECRET }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  data:
    - secretKey: AUTOBRR_SESSION_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 130220a1-4ccb-4e21-ada6-ef09e1614ba1
        property: session_secret
    - secretKey: AUTOBRR_POSTGRES_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 130220a1-4ccb-4e21-ada6-ef09e1614ba1
        property: pg_user
    - secretKey: AUTOBRR_POSTGRES_PASS
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 130220a1-4ccb-4e21-ada6-ef09e1614ba1
        property: pg_password

    - secretKey: POSTGRES_SUPER_USER
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: username
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: password
