apiVersion: v1
kind: Secret
metadata:
    name: discord-template-notifier-secret
    namespace: default
stringData:
    config.toml: ENC[AES256_GCM,data:cI+CKSqEPRPqKtKim35h0xZOseBdNrPq6l3wJOaVRcn98TAyb3ze5l3Oc9hhb2rc1wkSooXEs2KS6K59sSjH0fuG0EOaz2wvWHgjDs7ksgG2W4mxWpKe0URYCX4o+aAsBE8eZcpkXJl85qyznu9PP6iOTXakERe8PYBK29r5/DRwXResGB410g2WV1ycPgSIyVpsKf6Q9x5kZ+d08p6PRuemuRdPTkJjTQW7RoQN1fU15j8lLbtY+APj83vwLGmXJaFRjpV1lrtgpt6ncmrJdzX9xtqYVNcYTiLz4bAtJlMSlXGqK6RLci5UlotNbTZkPzYn5NNV+dHeyg2jrC6b0pEmLjgmc0TySsGhW5VPfDa2njf3dVvnbg0zuBmqXKLL5w==,iv:+EJSGIjJoOuNQQ6g2GT6sgc5wUhdL95UawrM5Y4c1dI=,tag:+YdSTf6O2Nb7gAGzyHzHmA==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age126422qm0mrq0tpmm0rjcacjznz8ggcf2map6yrz3y944e8x4tansxe73l5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSEdBTnhYOG96SSsvL1NW
            Q29zN1RUWGp5ZDR1M3U1bnpVMkxOVzgxdFFjCjgweG43bldCL1AwV1dsbjM4ektx
            K0ZtUW1mQ1dxaDFjS2svM0dmMGJtaTAKLS0tIE5GamdkVCsxZDM5OWV0QkJmOGhH
            bWZtNlBoclpUckZHQkRvUUhjcUtmK0kKvDKxAAAv5dqvIWIuXleFanAEpmEr5NUw
            bTnEaHea31xBfpMcEifbehuruO1nHzeRpmhOEbNUygExcHG13OoWgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-02T20:42:17Z"
    mac: ENC[AES256_GCM,data:RfORRwDUNCF2fDjD3ZeFfB3m0+rVD98OapuZtONQ+Fgg/5Ju63uF/xGK8djkfdkXiDTncNfE+dCTUXFS08YaItyEWDSl1ECaYTYxBViANi3H5TBhcdYowj8DMBuVwn4p/7pCP9HDflP6KwwI6vpkKu7mjshGB9GAAesA8M2avew=,iv:pnhwxC1zG1xO2SskTY1NA41UvJyZrPXS9ZG3oftcK74=,tag:OQSicp7iakFy56TI9M2FpA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
