---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        MINIO_ROOT_USER: "{{ .MINIO_ROOT_USER }}"
        MINIO_ROOT_PASSWORD: "{{ .MINIO_ROOT_PASSWORD }}"
        #MINIO_IDENTITY_OPENID_CLIENT_ID: "{{ .MINIO_OIDC_CLIENT_ID }}"
        #MINIO_IDENTITY_OPENID_CLIENT_SECRET: "{{ .MINIO_OIDC_CLIENT_SECRET }}"
  data:
    - secretKey: MINIO_ROOT_USER
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 93284d7d-4826-401d-bed2-e2db0579ced4
        property: username
    - secretKey: MINIO_ROOT_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 93284d7d-4826-401d-bed2-e2db0579ced4
        property: password

    #- secretKey: MINIO_OIDC_CLIENT_ID
    #  sourceRef:
    #    storeRef:
    #      name: bitwarden-fields
    #      kind: ClusterSecretStore
    #  remoteRef:
    #    key: 93284d7d-4826-401d-bed2-e2db0579ced4
    #    property: openid_client_id
    #- secretKey: MINIO_OIDC_CLIENT_SECRET
    #  sourceRef:
    #    storeRef:
    #      name: bitwarden-fields
    #      kind: ClusterSecretStore
    #  remoteRef:
    #    key: 93284d7d-4826-401d-bed2-e2db0579ced4
    #    property: openid_client_secret
