---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: privatebin-secret
  namespace: selfhosted
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        DB_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        DB_PORT: "5432"
        DB_USER: &dbUser "{{ .PRIVATEBIN__DB_USER }}"
        DB_PASS: &dbPass "{{ .PRIVATEBIN__DB_PASS }}"
        DB_NAME: &dbName privatebin
        confphp: "{{ .PRIVATEBIN__CONFPHP }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  data:
    - secretKey: PRIVATEBIN__DB_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: af193a34-8a66-44a5-b959-23a56adf19ac
        property: pg_user
    - secretKey: PRIVATEBIN__DB_PASS
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: af193a34-8a66-44a5-b959-23a56adf19ac
        property: pg_password

    - secretKey: PRIVATEBIN__CONFPHP
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
      remoteRef:
        key: af193a34-8a66-44a5-b959-23a56adf19ac

    - secretKey: POSTGRES_SUPER_USER
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: username
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: password
