---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: privatebin
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      main:
        #type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          enableServiceLinks: false
          securityContext:
            runAsUser: 65534
            runAsGroup: 82
            fsgroup: 82
            fsGroupChangePolicy: OnRootMismatch
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false

        #statefulset:
        #  volumeClaimTemplates:
        #    - name: data
        #      accessMode: ReadWriteMany
        #      size: 5Gi
        #      storageClass: cephfs
        #      globalMounts:
        #        - path: /srv/data

        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
              pullPolicy: IfNotPresent
            envFrom: &envFrom
              - secretRef:
                  name: privatebin-secret

        containers:
          main:
            image:
              #repository: ghcr.io/privatebin/nginx-fpm-alpine
              repository: ghcr.io/privatebin/pdo
              tag: 1.6.2
            env:
              TZ: "${TIMEZONE}"
              PHP_TZ: "${TIMEZONE}"
            envFrom: *envFrom
            resources:
              requests:
                cpu: 12m
                memory: 256M
              limits:
                memory: 512M
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          #external-dns.alpha.kubernetes.io/target: |-
          #  "external.${SECRET_DOMAIN},external.${SECRET_DOMAIN_2},external.${SECRET_DOMAIN_3},external.${SECRET_DOMAIN_4}"
        hosts:
          - host: &host "paste.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
          #- host: &host2 "paste.${SECRET_DOMAIN_2}"
          #  paths:
          #    - path: /
          #      service:
          #        name: main
          #        port: http
          #- host: &host3 "paste.${SECRET_DOMAIN_3}"
          #  paths:
          #    - path: /
          #      service:
          #        name: main
          #        port: http
          #- host: &host4 "paste.${SECRET_DOMAIN_4}"
          #  paths:
          #    - path: /
          #      service:
          #        name: main
          #        port: http
        tls:
          - hosts:
              - *host
          #  secretName: "${SECRET_DOMAIN/./-}-production-tls"
          #- hosts:
          #    - *host2
          #  secretName: "${SECRET_DOMAIN_2/./-}-production-tls"
          #- hosts:
          #    - *host3
          #  secretName: "${SECRET_DOMAIN_3/./-}-production-tls"
          #- hosts:
          #    - *host4
          #  secretName: "${SECRET_DOMAIN_4/./-}-production-tls"
    persistence:
      config:
        enabled: true
        type: configMap
        name: privatebin-configmap
        defaultMode: 0664
        globalMounts:
          - path: /srv/cfg/conf.php
            subPath: conf.php
            readOnly: true
