---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gotosocial-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        GTS_DB_TYPE: postgres
        GTS_DB_ADDRESS: &dbHost postgres16-rw.database.svc.cluster.local
        GTS_DB_PORT: "5432"
        GTS_DB_USER: &dbUser "{{ .GTS__DB_USER }}"
        GTS_DB_PASSWORD: &dbPass "{{ .GTS__DB_PASSWORD }}"
        GTS_DB_DATABASE: &dbName gotosocial
        GTS_DB_TLS_MODE: "disable"
        # OIDC
        #GTS_OIDC_CLIENT_ID: "{{ .GTS__OIDC_CLIENT_ID }}"
        #GTS_OIDC_CLIENT_SECRET: "{{ .GTS__OIDC_CLIENT_SECRET }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  data:
    - secretKey: GTS__DB_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: b13960fb-1175-444d-8d22-6bce5815baa9
        property: pg_user
    - secretKey: GTS__DB_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: b13960fb-1175-444d-8d22-6bce5815baa9
        property: pg_password

    - secretKey: GTS__OIDC_CLIENT_ID
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: b13960fb-1175-444d-8d22-6bce5815baa9
        property: oidc_client_id
    - secretKey: GTS__OIDC_CLIENT_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: b13960fb-1175-444d-8d22-6bce5815baa9
        property: oidc_client_secret

    - secretKey: POSTGRES_SUPER_USER
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: username
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: password

