---
apiVersion: mariadb.mmontes.io/v1alpha1
kind: Backup
metadata:
  name: wordpress
spec:
  mariaDbRef:
    name: mariadb-galera
  schedule:
    cron: "15 * * * *"
  maxRetentionDays: 14
  storage:
    volume:
      nfs:
        server: "${NAS_HOST}"
        path: /volume1/Media/mariadb/wordpress
  args:
    - --single-transaction
    - --databases wordpress
