---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app readarr
  namespace: flux-system
spec:
  targetNamespace: downloads
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: cloudnative-pg-cluster
    - name: external-secrets-bitwarden
  path: ./kubernetes/apps/downloads/readarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 2Gi
      #VOLSYNC_STORAGECLASS: ceph-block
      #VOLSYNC_SNAPSHOTCLASS: csi-ceph-blockpool
      VOLSYNC_UID: "1031"
