---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vector-aggregator
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        GEOIPUPDATE_ACCOUNT_ID: "{{ .MAXMIND_ACCOUNT_ID }}"
        GEOIPUPDATE_LICENSE_KEY: "{{ .MAXMIND_LICENSE_KEY }}"
  data:
    - secretKey: MAXMIND_ACCOUNT_ID
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: a8f89a1b-e789-4296-a8fb-b0d5012ea283
        property: MAXMIND_ACCOUNT_ID
    - secretKey: MAXMIND_LICENSE_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: a8f89a1b-e789-4296-a8fb-b0d5012ea283
        property: MAXMIND_LICENSE_KEY
