---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app wallabag
  namespace: flux-system
spec:
  targetNamespace: default
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 10m
  path: "./kubernetes/apps/default/wallabag/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: false
  dependsOn:
    - name: crunchy-postgres-operator
    - name: external-secrets-cluster-secrets
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: wallabag
