---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zipline-secret
  namespace: selfhosted
spec:
  target:
    name: zipline-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        CORE_SECRET: "{{ .core_secret }}"
        CORE_DATABASE_URL: "postgres://{{ .zipline_pg_user }}:{{ .zipline_pg_pass }}@postgres16-rw.database.svc.cluster.local:5432/zipline"
        DATASOURCE_S3_ACCESS_KEY_ID: "{{ .s3_access_key_id }}"
        DATASOURCE_S3_SECRET_ACCESS_KEY: "{{ .s3_secret_access_key }}"
        # OAuth (Discord)
        #OAUTH_DISCORD_CLIENT_ID: "{{ .discord_client_id }}"
        #OAUTH_DISCORD_CLIENT_SECRET: "{{ .discord_client_secret }}"
        # S3
        DATASOURCE_S3_ENDPOINT: "{{ .s3_endpoint_host }}"
        DATASOURCE_S3_PORT: "{{ .s3_endpoint_port }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: zipline
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .zipline_pg_user }}"
        INIT_POSTGRES_PASS: "{{ .zipline_pg_pass }}"
        INIT_POSTGRES_SUPER_USER: "{{ .pg_super_user }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .pg_super_pass }}"
  data:
    - secretKey: zipline_pg_user
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d38228c9-42d9-43e8-8259-003fd29c5883
        property: pg_user
    - secretKey: zipline_pg_pass
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d38228c9-42d9-43e8-8259-003fd29c5883
        property: pg_password

    - secretKey: core_secret
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d38228c9-42d9-43e8-8259-003fd29c5883
        property: core_secret

    - secretKey: s3_endpoint_host
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: c9cefb83-f535-4d28-965e-523667932959
        property: endpoint_host
    - secretKey: s3_endpoint_port
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: c9cefb83-f535-4d28-965e-523667932959
        property: endpoint_Port


    - secretKey: s3_access_key_id
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d38228c9-42d9-43e8-8259-003fd29c5883
        property: s3_access_key_id
    - secretKey: s3_secret_access_key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d38228c9-42d9-43e8-8259-003fd29c5883
        property: s3_secret_access_key

    - secretKey: pg_super_user
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: username
    - secretKey: pg_super_pass
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: password
