---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: zipline
  namespace: selfhosted
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false

    controllers:
      main:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"

        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
            imagePullPolicy: IfNotPresent
            envFrom: &envFrom
              - secretRef:
                  name: zipline-secret

        containers:
          main:
            image:
              repository: ghcr.io/diced/zipline
              tag: 3.7.8
            env:
              TZ: ${TIMEZONE}
              # Core config
              CORE_LOGGER: "true"
              CORE_RETURN_HTTPS: "true"
              #CORE_COMPRESSION_ENABLED: "true"
              #CORE_COMPRESSION_THRESHOLD: "200mb"
              #CORE_COMPRESSION_ON_DASHBOARD: "true"
              #CORE_HTTPS: "true"
              CORE_HOST: "0.0.0.0"
              CORE_PORT: "3000"
              CORE_DATABASE_URL:
                valueFrom:
                  secretKeyRef:
                    name: zipline-secret
                    key: CORE_DATABASE_URL
              CORE_SECRET:
                valueFrom:
                  secretKeyRef:
                    name: zipline-secret
                    key: CORE_SECRET

              # Datasources
              #DATASOURCE_TYPE: local
              #DATASOURCE_LOCAL_DIRECTORY: ./uploads
              DATASOURCE_TYPE: s3
              DATASOURCE_S3_ACCESS_KEY_ID:
                valueFrom:
                  secretKeyRef:
                    name: zipline-secret
                    key: DATASOURCE_S3_ACCESS_KEY_ID
              DATASOURCE_S3_SECRET_ACCESS_KEY:
                valueFrom:
                  secretKeyRef:
                    name: zipline-secret
                    key: DATASOURCE_S3_SECRET_ACCESS_KEY
              DATASOURCE_S3_ENDPOINT:
                valueFrom:
                  secretKeyRef:
                    name: zipline-secret
                    key: DATASOURCE_S3_ENDPOINT
              DATASOURCE_S3_PORT:
                valueFrom:
                  secretKeyRef:
                    name: zipline-secret
                    key: DATASOURCE_S3_PORT
              DATASOURCE_S3_BUCKET: zipline
              DATASOURCE_S3_REGION: ca-east-1
              DATASOURCE_S3_USE_SSL: "false"

              #OAUTH_DISCORD_CLIENT_ID:
              #  valueFrom:
              #    secretKeyRef:
              #      name: zipline-secret
              #      key: OAUTH_DISCORD_CLIENT_ID
              #OAUTH_DISCORD_CLIENT_SECRET:
              #  valueFrom:
              #    secretKeyRef:
              #      name: zipline-secret
              #      key: OAUTH_DISCORD_CLIENT_SECRET

              # Exif
              #EXIF_ENABLED: "false"
              #EXIF_REMOVE_GPS: "true"

              # Features
              #FEATURES_INVITES: "false"
              #FEATURES_INVITES_LENGTH: "16"
              #FEATURES_ROBOTS_TXT: "true"
              #FEATURES_OAUTH_REGISTRATION: "false"
              #FEATURES_USER_REGISTRATION: "false"
              #FEATURES_HEADLESS: "false"

              # Uploader
              #UPLOADER_DEFAULT_FORMAT: DATE
              UPLOADER_DEFAULT_FORMAT: RANDOM
              UPLOADER_ROUTE: /file
              UPLOADER_ADMIN_LIMIT: 100gb
              UPLOADER_USER_LIMIT: 500mb
              UPLOADER_DISABLED_EXTENSIONS: ps1,pdf,bat,exe,sh,fish
              #UPLOADER_FORMAT_DATE: "YYYY-MM-DD_HH-mm-ss"
              #UPLOADER_DEFAULT_EXPIRATION: ""

              # Ratelimit
              #RATELIMIT_USER: "5"
              #RATELIMIT_ADMIN: "1"

              # URLs
              URLS_ROUTE: /go
              URLS_LENGTH: "6"

              # Website
              WEBSITE_TITLE: Zipline
              #WEBSITE_SHOW_FILES_PER_USER: "false"
              #WEBSITE_EXTERNAL_LINKS: '[{label:Admin: Aumer,link:https://${SECRET_DOMAIN}},{label:Powered by Zipline,link:https://github.com/diced/zipline}]'
              #WEBSITE_SHOW_VERSION: "false"
              #WEBSITE_DISABLE_MEDIA_PREVIEW: "false"
            #envFrom: *envFrom
            resources:
              requests:
                cpu: 5m
                memory: 256Mi
              limits:
                memory: 4000Mi
            #resources:
            #  requests:
            #    cpu: 10m
            #    memory: 128Mi
            #  limits:
            #    memory: 4000Mi
            #podSecurityContext:
            #  runAsUser: 568
            #  runAsGroup: 568
            #  fsGroup: 568
            #  fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        ports:
          http:
            port: 3000
    ingress:
      main:
        enabled: true
        className: external
        annotations:
          hajimari.io/icon: pajamas:media
          nginx.ingress.kubernetes.io/proxy-body-size: "100m"
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "zipline.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
