#---
#apiVersion: storage.k8s.io/v1
#kind: StorageClass
#metadata:
#  name: synology-nfs
#provisioner: nfs.csi.k8s.io
#parameters:
#  server: mega.home.ld
#  share: /volume1/kubes
#reclaimPolicy: Delete
#volumeBindingMode: Immediate
#mountOptions:
#  - nfsvers=4.0
#  - nconnect=8
#  - hard
#  - noatime
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gluster-nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: gfs.home.ld
  share: /gv0
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.0
  - nconnect=8
  - hard
  - noatime
