---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # Authentik
        GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "{{ .client_id }}"
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{ .client_secret }}"
        # Admin User
        adminUser: "{{ .adminUser }}"
        adminPass: "{{ .adminPass }}"
        # App
        GF_DATABASE_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        GF_DATABASE_PORT: "5432"
        GF_DATABASE_USER: &dbUser "{{ .GF_DATABASE_USER }}"
        GF_DATABASE_PASSWORD: &dbPass "{{ .GF_DATABASE_PASSWORD }}"
        GF_DATABASE_NAME: &dbName grafana
        GF_DATABASE_SSL_MODE: disable
        GF_DATABASE_TYPE: postgres
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # Pushover
        PUSHOVER_TOKEN: "{{ .GRAFANA__PUSHOVER_TOKEN }}"
        PUSHOVER_USER_KEY: "{{ .GRAFANA__PUSHOVER_USER_KEY }}"
  data:
    - secretKey: client_id
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 59c71d93-847f-4d54-8583-1c8268f68431
        property: client_id
    - secretKey: client_secret
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 59c71d93-847f-4d54-8583-1c8268f68431
        property: client_secret

    - secretKey: adminUser
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 59c71d93-847f-4d54-8583-1c8268f68431
        property: username
    - secretKey: adminPass
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 59c71d93-847f-4d54-8583-1c8268f68431
        property: password

    - secretKey: GF_DATABASE_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 59c71d93-847f-4d54-8583-1c8268f68431
        property: pg_user
    - secretKey: GF_DATABASE_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 59c71d93-847f-4d54-8583-1c8268f68431
        property: pg_password

    - secretKey: POSTGRES_SUPER_USER
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: username
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: password

    - secretKey: GRAFANA__PUSHOVER_TOKEN
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 30fb1e5e-951c-4c2b-b30a-0af2e38ca5cc
        property: username
    - secretKey: GRAFANA__PUSHOVER_USER_KEY
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 30fb1e5e-951c-4c2b-b30a-0af2e38ca5cc
        property: password
