apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:ZWBEsRieQ6H1Pw3x2p3Pv5uBmkMsdp//,iv:Wso4mEiii56jdNfdYvajcgbyoqUJrhD1Xu8+IazGdyc=,tag:yLy+bVCYKk8xw2J8RFCz+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age126422qm0mrq0tpmm0rjcacjznz8ggcf2map6yrz3y944e8x4tansxe73l5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VzQ2VWJ5Q0o3L3BJVmhI
            RDVOYjIyTEJsenZmTUJMdVBpajNpR3c3T1ZzCmtlQ2VUMmFUWS9BcEtZREJHNmxr
            b1BzM09qeTdiMDJaRVRYeEs2dVgzVDAKLS0tIFlweWdENFZUYk5FYVY3eFc5VDdv
            WTZQejNSZFZLZ084Yk1JRFVMWWxTZHcK3bAOBVQdywPGjsOyRK7Q1nCkRGeJ2M14
            lh1dx2W9gYhghOMtnUKihc2shmaFy5Gc1EH7rhKjbc2k3JRJENnaqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-27T07:20:33Z"
    mac: ENC[AES256_GCM,data:Rk2pZQa9l3YrQlvHKSzIzFOPotuEGcNs7Py5yUBBl1BUj6JDtXvh7AdsaRAePFIHc6qDDUoyzOo6x6mfpxI43bhLT21FC6HgUt2H1pY0HPMP1vrT0z3fS4BEMe5dAf3uY6d0of9U8CmKmtBPCnqYlR6QzlMVrsTbWGWDG1OQ/QU=,iv:4qE0le3kTq43gQcajsS42AWWez6vnmZdUEXGe14QZkg=,tag:PWoAuYWW3/9qu78q+kmFng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
