apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:THMVOAs+6vEloW8HQ/VljgDJdnkKYhHT,iv:nOZThreMddDVl4aRf2wxfe9WIvsogvbdhJiAzx3vcaM=,tag:KXXjIDsxXNLIG2ZhcnscYw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age126422qm0mrq0tpmm0rjcacjznz8ggcf2map6yrz3y944e8x4tansxe73l5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxT001U1ZpUC9TcHBzSVFY
            WmJyWDNFWHN0eFpnTjRKRWFsd0hSanFWK2lZClc1NjNZS3RMUkcxNW5zS3Z2VzNR
            clhqaHFCMGNOQ2tJZGVPR3dFVW1IL1kKLS0tIHArbDMraVJlYjhlVHZwTDc5NDda
            b2Zub1NnclliZHh2L3c1OE1sWjRrdWcKiKX19SZjQzTWp8CP57yp7aUEoWrA821a
            mzd94rHECHpnVjtdRagQnYWVfm3dXHziodtFs88K2jpZql/qlY5VWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-28T06:46:31Z"
    mac: ENC[AES256_GCM,data:/0wZFawcqc7rua9ipC9ASxMJfuYnvD3o818VrXVtGMuqb4pJJ18HA9psP1MdSoRzCHnF1J0lDPDwhbQ1JKD0fwJTbDivg9j4t1izXm+a8tCBMjNO1xFtc676Hv5rQ8+LWGi/X8fL/GT7JT1ZZUCuchFLmn0AOioH/y201oYlHL8=,iv:fYK2eGd/VcP/me2pJjIFE/XI5vdIji9hBu46+XWnxJc=,tag:TUiX7FxKU6ohdu8oJp3sRQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
