apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:kh3+eK89SJQgF2gmtgHAUlYQjkfVX5Is,iv:wQsXIJpcgKRsGcNevd5I8DBlsbaRf3R/Y+Rg7Bt+hLU=,tag:J6vWVmrT4z4lMX3JCRv/+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age126422qm0mrq0tpmm0rjcacjznz8ggcf2map6yrz3y944e8x4tansxe73l5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtOTBNak5FMTJ2N2lESlRy
            UjJPMTRaWktvU1NoeDQ5cWc4anBXWUhFeVE4CkJLd0RTTjMxZHpBNlRqcis5VmR5
            OElQOEwrUWU4dy8wRGV1OFVqaEI4VWcKLS0tIDJaZGg4SVFvYmtEVUR4bUxaYzlv
            Z28vT1E4N25QMjJzdCtVZ2lwajJHTG8Khl8CQe1bAa/vzrn00HM1Bjewd3v1cfxE
            NWixrI09S3x3c4m7kwE5Roc8qQOYsrPBW9JUV3Hc3EM2JtlXPVMsdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-22T02:07:19Z"
    mac: ENC[AES256_GCM,data:kgo2AGCLueeNGoKeHaYjPFE90L/LAvTyxD1FJKZOYiOH6TLeFJHJ+vZXdm3tGVN9s7fHIcOvssJZTCsSu/t98Itaiqw4io0atMz4vhEYgfV6aXT+QGT4ACCwzfNprd9KsRh7kWh5I92bWEgXQ0lwLDIhUaeWs8nbbhXo8hJqPHc=,iv:AW/6qNjXOVvecLSOzpzgdD+dkSuKuQIiXxzHp04bDKQ=,tag:1ewi+iW4S0DegHsfTlv59Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
