apiVersion: v1
kind: ConfigMap
metadata:
  name: hedgedoc-ldap-configmap
  namespace: selfhosted
data:
  CMD_LDAP_URL: ${LDAP_URL}
  CMD_LDAP_BINDDN: ${LDAP_READONLY_USER_BIND}
  CMD_LDAP_BINDCREDENTIALS: ${LDAP_READONLY_USER_PASSWORD}
  CMD_LDAP_SEARCHBASE: ${LDAP_BASE_DN}
  CMD_LDAP_SEARCHFILTER: (&(objectClass=user)(memberOf=cn=hedgedoc,ou=groups,dc=home,dc=ld)(cn={{username}}))
  CMD_LDAP_USERIDFIELD: cn
