---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hedgedoc-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        CMD_SESSION_SECRET: "{{ .HEDGEDOC__SESSION_SECRET }}"
        CMD_DB_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        CMD_DB_PORT: "5432"
        CMD_DB_DIALECT: postgres
        CMD_DB_DATABASE: &dbName hedgedoc
        CMD_DB_USERNAME: &dbUser "{{ .HEDGEDOC__POSTGRES_USER }}"
        CMD_DB_PASSWORD: &dbPass "{{ .HEDGEDOC__POSTGRES_PASSWORD }}"
        # S3 Upload
        CMD_MINIO_ACCESS_KEY: "{{ .HEDGEDOC__S3_ACCESS_KEY }}"
        CMD_MINIO_SECRET_KEY: "{{ .HEDGEDOC__S3_SECRET_KEY }}"
        CMD_MINIO_ENDPOINT: mega.home.ld
        CMD_MINIO_PORT: 9000
        CMD_MINIO_SECURE: false
        CMD_S3_BUCKET: hedgedoc
        # Authentik
        CMD_OAUTH2_CLIENT_ID: "{{ .HEDGEDOC__OAUTH_CLIENT_ID }}"
        CMD_OAUTH2_CLIENT_SECRET: "{{ .HEDGEDOC__OAUTH_CLIENT_SECRET }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  data:
    - secretKey: HEDGEDOC__SESSION_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 8298fbc6-4853-46c9-9844-e6daf62310dd
        property: session_token
    - secretKey: HEDGEDOC__POSTGRES_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 8298fbc6-4853-46c9-9844-e6daf62310dd
        property: pg_user
    - secretKey: HEDGEDOC__POSTGRES_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 8298fbc6-4853-46c9-9844-e6daf62310dd
        property: pg_password

    - secretKey: HEDGEDOC__S3_ACCESS_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 8298fbc6-4853-46c9-9844-e6daf62310dd
        property: s3_access_key
    - secretKey: HEDGEDOC__S3_SECRET_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 8298fbc6-4853-46c9-9844-e6daf62310dd
        property: s3_secret_key

    - secretKey: HEDGEDOC__OAUTH_CLIENT_ID
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 8298fbc6-4853-46c9-9844-e6daf62310dd
        property: oauth_client_id
    - secretKey: HEDGEDOC__OAUTH_CLIENT_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 8298fbc6-4853-46c9-9844-e6daf62310dd
        property: oauth_client_secret
    - secretKey: POSTGRES_SUPER_USER
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: username
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: password

