---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: selfhosted
resources:
  #- ./configmap.yaml
  - ./external-secret.yaml
  - ./helmrelease.yaml
  - ../../../../templates/gatus/external
  #- ../../../../templates/volsync
configMapGenerator:
  - name: hedgedoc-configmap
    files:
      - config.json=./config/config.json
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
