---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app actual
  namespace: flux-system
spec:
  targetNamespace: finance
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: longhorn
    - name: volsync
  path: ./kubernetes/apps/finance/actual/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: budget
      HOSTNAME: budget.${SECRET_DOMAIN}
      VOLSYNC_CAPACITY: 1Gi
      VOLSYNC_ACCESSMODES: ReadWriteOnce
      VOLSYNC_STORAGECLASS: longhorn-snapshot
      VOLSYNC_SNAPSHOTCLASS: longhorn-snapclass
      VOLSYNC_UID: "568"
      VOLSYNC_GID: "568"
      VOLSYNC_CLAIM: actual-data
