---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bookstack-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        APP_KEY: "{{ .BOOKSTACK__APP_KEY }}"
        DB_HOST: mariadb-galera-primary.database.svc.cluster.local:3306
        DB_DATABASE: bookstack
        DB_USERNAME: "{{ .BOOKSTACK__DB_USER }}"
        DB_PASSWORD: "{{ .BOOKSTACK__DB_PASS }}"
  data:
    - secretKey: BOOKSTACK__APP_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d78ac4e2-1769-49b7-aac7-afb8caf9d3dc
        property: app_key

    - secretKey: BOOKSTACK__DB_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d78ac4e2-1769-49b7-aac7-afb8caf9d3dc
        property: mariadb_user
    - secretKey: BOOKSTACK__DB_PASS
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d78ac4e2-1769-49b7-aac7-afb8caf9d3dc
        property: mariadb_password
