---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: recyclarr-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        RADARR_API_KEY: |-
          {{ .radarr_token }}
        SONARR_API_KEY: |-
          {{ .sonarr_token }}
  data:
    - secretKey: radarr_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: a8382e67-3d4f-4cc7-8f84-a391c1fcfad6
        property: token
    - secretKey: sonarr_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 0297ca08-5770-4ce4-8a03-d1d95003e90b
        property: token
