---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authelia-secret
  namespace: system
spec:
  target:
    name: authelia-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        AUTHELIA_AUTHENTICATION_BACKEND_LDAP_USER: "{{ .lldap_user_dn }}"
        AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD: "{{ .lldap_password }}"
        AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET: "{{ .hmac_secret }}"
        AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY: "{{ .authelia_oidc_issuer_private_key }}"
        AUTHELIA_JWT_SECRET: "{{ .jwt_secret }}"
        AUTHELIA_SESSION_SECRET: "{{ .session_secret }}"
        AUTHELIA_STORAGE_ENCRYPTION_KEY: "{{ .storage_encryption_key }}"
        #AUTHELIA_NOTIFIER_SMTP_USERNAME: "{{ .authelia_smtp_username }}"
        #AUTHELIA_NOTIFIER_SMTP_PASSWORD: "{{ .authelia_smtp_password }}"
        #AUTHELIA_NOTIFIER_SMTP_SENDER: "{{ .authelia_smtp_sender }}"
        # Clients
        GRAFANA_OAUTH_CLIENT_SECRET: "{{ .authelia_grafana_oauth_client_secret }}"
        #OUTLINE_OAUTH_CLIENT_SECRET: "{{ .authelia_outline_oauth_client_secret }}"
        # Database
        AUTHELIA_STORAGE_POSTGRES_DATABASE: &dbName authelia
        AUTHELIA_STORAGE_POSTGRES_ADDRESS: &dbHost postgres16-rw.database.svc.cluster.local
        AUTHELIA_STORAGE_POSTGRES_USERNAME: &dbUser "{{ .AUTHELIA_STORAGE_POSTGRES_USERNAME }}"
        AUTHELIA_STORAGE_POSTGRES_PASSWORD: &dbPass "{{ .AUTHELIA_STORAGE_POSTGRES_PASSWORD }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  data:
    - secretKey: lldap_user_dn
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 1e547e6b-c279-4eaa-94ba-6bfe45c972a2
        property: username
    - secretKey: lldap_password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 1e547e6b-c279-4eaa-94ba-6bfe45c972a2
        property: password
    - secretKey: authelia_oidc_hmac_secret
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: cd732c61-c63d-410c-a634-d195bd8cf870
        property: hmac_secret
    - secretKey: authelia_oidc_issuer_private_key
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
      remoteRef:
        key: cd732c61-c63d-410c-a634-d195bd8cf870
    - secretKey: authelia_jwt_secret
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: cd732c61-c63d-410c-a634-d195bd8cf870
        property: jwt_secret
    - secretKey: authelia_session_secret
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: cd732c61-c63d-410c-a634-d195bd8cf870
        property: session_secret
    - secretKey: authelia_storage_encryption_key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: cd732c61-c63d-410c-a634-d195bd8cf870
        property: storage_encryption_key
    #- secretKey: authelia_smtp_username
    #  sourceRef:
    #    storeRef:
    #      name: bitwarden-fields
    #      kind: ClusterSecretStore
    #  remoteRef:
    #    key: 94348ad9-8138-4bf5-8c54-b0490134df30
    #    property: authelia_smtp_username
    #- secretKey: authelia_smtp_password
    #  sourceRef:
    #    storeRef:
    #      name: bitwarden-fields
    #      kind: ClusterSecretStore
    #  remoteRef:
    #    key: 94348ad9-8138-4bf5-8c54-b0490134df30
    #    property: authelia_smtp_password
    #- secretKey: authelia_smtp_sender
    #  sourceRef:
    #    storeRef:
    #      name: bitwarden-fields
    #      kind: ClusterSecretStore
    #  remoteRef:
    #    key: 94348ad9-8138-4bf5-8c54-b0490134df30
    #    property: authelia_smtp_sender
    - secretKey: authelia_grafana_oauth_client_secret
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: cd732c61-c63d-410c-a634-d195bd8cf870
        property: grafana_oauth_client_secret
    #- secretKey: authelia_outline_oauth_client_secret
    #  sourceRef:
    #    storeRef:
    #      name: bitwarden-fields
    #      kind: ClusterSecretStore
    #  remoteRef:
    #    key: 94348ad9-8138-4bf5-8c54-b0490134df30
    #    property: authelia_outline_oauth_client_secret
    - secretKey: AUTHELIA_STORAGE_POSTGRES_USERNAME
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: cd732c61-c63d-410c-a634-d195bd8cf870
        property: pg_user
    - secretKey: AUTHELIA_STORAGE_POSTGRES_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: cd732c61-c63d-410c-a634-d195bd8cf870
        property: pg_password
    - secretKey: POSTGRES_SUPER_USER
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: username
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: password
