---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  #- ./downloads-pvc.yaml
  # Flux-Kustomizations
  - ./autobrr/ks.yaml
  #- ./bazarr/ks.yaml
  - ./cross-seed/ks.yaml
  - ./flaresolverr/ks.yaml
  ##- ./frigate/ks.yaml
  ##- ./kubernetes-schemas/ks.yaml
  - ./lidarr/ks.yaml
  ##- ./media-browser/ks.yaml
  - ./overseerr/ks.yaml
  - ./prowlarr/ks.yaml
  #- ./qbittorrent/ks.yaml
  - ./radarr/ks.yaml
  - ./readarr/ks.yaml
  - ./recyclarr/ks.yaml
  - ./sabnzbd/ks.yaml
  ##- ./slskd/ks.yaml
  - ./sonarr/ks.yaml
  - ./unpackerr/ks.yaml
