---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wikijs-secret
  namespace: selfhosted
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        DB_TYPE: postgres
        DB_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        DB_PORT: "5432"
        DB_NAME: &dbName wikijs
        DB_USER: &dbUser "{{ .WIKIJS__POSTGRES_USER }}"
        DB_PASS: &dbPass "{{ .WIKIJS__POSTGRES_PASSWORD }}"
        # Authentik
        #CMD_OAUTH2_CLIENT_ID: "{{ .WIKIJS__OAUTH_CLIENT_ID }}"
        #CMD_OAUTH2_CLIENT_SECRET: "{{ .WIKIJS__OAUTH_CLIENT_SECRET }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  data:
    - secretKey: WIKIJS__POSTGRES_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: ff80ece2-d9db-49d3-9a5a-b6788c32d2be
        property: pg_user
    - secretKey: WIKIJS__POSTGRES_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: ff80ece2-d9db-49d3-9a5a-b6788c32d2be
        property: pg_password
    - secretKey: POSTGRES_SUPER_USER
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: username
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: password

