---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: shiori-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        SHIORI_DATABASE_URL: "postgres://{{ .SHIORI__POSTGRES_USER }}:{{ .SHIORI__POSTGRES_PASS }}@postgres16-rw.database.svc.cluster.local:5432/shiori"
        # Postgres Init
        INIT_POSTGRES_DBNAME: shiori
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .SHIORI__POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .SHIORI__POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  data:
    - secretKey: SHIORI__POSTGRES_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 419bcb9b-6595-4a79-a9cc-1113a4fb32dc
        property: pg_user
    - secretKey: SHIORI__POSTGRES_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 419bcb9b-6595-4a79-a9cc-1113a4fb32dc
        property: pg_password

    - secretKey: POSTGRES_SUPER_USER
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: username
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: password

