---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: selfhosted
resources:
  - ./external-secret.yaml
  - ./helmrelease.yaml
  - ../../../../templates/gatus/external
  - ../../../../templates/volsync
