---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-secrets
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # Authentik
        AUTHENTIK_SECRET_KEY: "{{ .AUTHENTIK_SECRET_KEY }}"
        AUTHENTIK_REDIS__HOST: redis.database.svc.cluster.local
        AUTHENTIK_POSTGRESQL__USER: "{{ .AUTHENTIK_DATABASE_USER }}"
        AUTHENTIK_POSTGRESQL__PASSWORD: "{{ .AUTHENTIK_DATABASE_PASSWORD }}"
        AUTHENTIK_POSTGRESQL__HOST: &dbHost postgres16-rw.database.svc.cluster.local
        AUTHENTIK_POSTGRESQL__NAME: &dbName authentik
        #AUTHENTIK_EMAIL__USERNAME: "{{ .AUTHENTIK_EMAIL__USERNAME }}"
        #AUTHENTIK_EMAIL__PASSWORD: "{{ .AUTHENTIK_EMAIL__PASSWORD }}"
        AUTHENTIK_BOOTSTRAP_EMAIL: "{{ .AUTHENTIK_BOOTSTRAP_EMAIL }}"
        AUTHENTIK_BOOTSTRAP_PASSWORD: "{{ .AUTHENTIK_BOOTSTRAP_PASSWORD }}"
        AUTHENTIK_BOOTSTRAP_TOKEN: "{{ .AUTHENTIK_BOOTSTRAP_TOKEN }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: "{{ .AUTHENTIK_DATABASE_USER }}"
        INIT_POSTGRES_PASS: "{{ .AUTHENTIK_DATABASE_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  data:
    - secretKey: AUTHENTIK_DATABASE_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 5c98c9a2-fc81-4dff-91ff-0c1e10d32c9d
        property: pg_user
    - secretKey: AUTHENTIK_DATABASE_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 5c98c9a2-fc81-4dff-91ff-0c1e10d32c9d
        property: pg_password
    - secretKey: AUTHENTIK_SECRET_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 5c98c9a2-fc81-4dff-91ff-0c1e10d32c9d
        property: secret_key
    #- secretKey: AUTHENTIK_EMAIL__USERNAME
    #  sourceRef:
    #    storeRef:
    #      name: bitwarden-login
    #      kind: ClusterSecretStore
    #  remoteRef:
    #    key: e09429a9-e6ef-49a1-bd0a-afc50145dc9c
    #    property: username
    #- secretKey: AUTHENTIK_EMAIL__PASSWORD
    #  sourceRef:
    #    storeRef:
    #      name: bitwarden-login
    #      kind: ClusterSecretStore
    #  remoteRef:
    #    key: e09429a9-e6ef-49a1-bd0a-afc50145dc9c
    #    property: password
    - secretKey: AUTHENTIK_BOOTSTRAP_EMAIL
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 5c98c9a2-fc81-4dff-91ff-0c1e10d32c9d
        property: username
    - secretKey: AUTHENTIK_BOOTSTRAP_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 5c98c9a2-fc81-4dff-91ff-0c1e10d32c9d
        property: password
    - secretKey: AUTHENTIK_BOOTSTRAP_TOKEN
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 5c98c9a2-fc81-4dff-91ff-0c1e10d32c9d
        property: token
    - secretKey: POSTGRES_SUPER_USER
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: username
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: password
