---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: 2023.10.4
      sourceRef:
        kind: HelmRepository
        name: authentik-charts
        namespace: flux-system
      interval: 5m
  #dependsOn:
  #  - name: cloudnative-pg
  #    namespace: database
  values:
    initContainers:
      init-db:
        image:
          repository: ghcr.io/onedr0p/postgres-init
          tag: 15
          pullPolicy: IfNotPresent
        envFrom: &envFrom
          - secretRef:
              name: authentik-secrets
    #initContainers:
    #  init-db:
    #    image: ghcr.io/onedr0p/postgres-init:15
    #    imagePullPolicy: IfNotPresent
    #    envFrom:
    #      - secretRef:
    #          name: authentik-secrets
    podAnnotations:
      secret.reloader.stakater.com/reload: authentik-secrets
    ingress:
      enabled: true
      ingressClassName: external
      annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/icon: authentik.png
        gethomepage.dev/name: Authentik
        gethomepage.dev/group: Infrastructure
        gethomepage.dev/widget.type: authentik
        gethomepage.dev/widget.url: https://authentik.${SECRET_DOMAIN}
        gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_AUTHENTIK_TOKEN}}"
        external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
      hosts:
        - host: &host authentik.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
          secretName: *host
    envFrom:
      - secretRef:
          name: authentik-secrets
    postgresql:
      enabled: false
    redis:
      enabled: false
    geoip:
      enabled: false
    prometheus:
      rules:
        create: true
      serviceMonitor:
        create: true
    authentik:
      email:
        from: "id@${SECRET_DOMAIN}"
        host: "mail1.home.ld"
        port: "25"
        use_ssl: false
      outposts:
        docker_image_base: ghcr.io/goauthentik/%(type)s:%(version)s
