apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "${SECRET_ACME_EMAIL}"
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token
        selector:
          dnsZones:
            - "${SECRET_DOMAIN}"
            - "${SECRET_DOMAIN_2}"
            - "${SECRET_DOMAIN_3}"
            - "${SECRET_DOMAIN_4}"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: "${SECRET_ACME_EMAIL}"
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token
        selector:
          dnsZones:
            - "${SECRET_DOMAIN}"
            - "${SECRET_DOMAIN_2}"
            - "${SECRET_DOMAIN_3}"
            - "${SECRET_DOMAIN_4}"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme.zerossl.com/v2/DV90
    email: "${SECRET_ACME_EMAIL}"
    privateKeySecretRef:
      name: zerossl-production
    externalAccountBinding:
      keyID: "${ZEROSSL_EAB_KEY_ID}"
      keySecretRef:
        name: cert-manager-secret
        key: zerossl_eab_hmac_key
      keyAlgorithm: "${ZEROSSL_KEY_ALGO}"
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token
        selector:
          dnsZones:
            - "${SECRET_DOMAIN}"
            - "${SECRET_DOMAIN_2}"
            - "${SECRET_DOMAIN_3}"
            - "${SECRET_DOMAIN_4}"
