apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:d8SHMKWqsb/HowhqVWzoHgSJnZ+urs1/bvHdHbW9tc9NxmVWylKXzQ==,iv:dlhL0oC3C87yoLyUjpBn0EuYfU+Z3PQ1tkKEdTv+Luw=,tag:DdW/+8iCdpkgUI3InOVWVA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age126422qm0mrq0tpmm0rjcacjznz8ggcf2map6yrz3y944e8x4tansxe73l5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ZjFEWEVMZHdaUjBGa1hv
            ZS9hRlJJOGJqRE9GNjNvWHFsSDk4R3IzNWdZCmcvcG5WZC9aYkVIQmFhMi9iQTNR
            aGt1UnZBK3dYRDh4L2NVeG9EbTMwMk0KLS0tIEFVL1NLTWV0dk1ObnYzalN0UmpH
            eXJ1Zk14bUNDd0NSQTdYTlAvdXlTUlEKxLJIQ3Fsa6YExtJIYypnsByhf9PHFSBb
            J7aOTPwnd/a2VP2BTbi9H+ZnqL06Tbzk2b3CadOSrjDWlvuwh1hugw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-22T02:07:19Z"
    mac: ENC[AES256_GCM,data:syYyt0guoMn0mOan5iy/4h3cWyE5Nxlf/6mCdFh95CoNqlI46f3K6Yf/+LPOZwcKGRloOgImjhH0euLNF+F6Kkx1ukFbCIuKYOeiY3Bk5XTP9c63cvV/8Y15AXI+1lus4idf9EmIyuiOkO2QqB92oL4lU3n3uQ/HRsczwh9fwm8=,iv:9kxKOiVf00DGpgGlJ9aVdzFF6WYPCr/HOCNa7PWhY8g=,tag:uCDVUZmeLuRPRFJzqzwIng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
