apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:pN5xq1y4YHkM3FplH155N92Lo7c2SHta/IcUsFYbqhPhNNoS+zaHpQ==,iv:n2bg8da/kh4OzYzsDqX3k8TgaCuPZRBpiva8zFccuNk=,tag:BUOxa9X+TmKGbqiBcBdM/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age126422qm0mrq0tpmm0rjcacjznz8ggcf2map6yrz3y944e8x4tansxe73l5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUDA4THpHV2pqL2NveEdV
            SUFkaHNwaDFnb05tcHgrQkpIcGZCNi9WSWlBCmdONUZ6UEgrZHpvQjNzYWJpMXVr
            OGxVb3o0b3RMazEwRVdXZys5K04zczgKLS0tIEp2aDhxNnVaZUlueDVlbkJDeHo3
            UjZYbFhuNUdmSllyZXBKVmUrcG9xdXMK8m0DKZnuW38lZAQKFHwmVRemozgRBbZB
            zggzXfQhvc4hTySGiMPyw2z2iBEGLCy6Z6Nbn/jOIO+XOXU330wLnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-21T23:38:00Z"
    mac: ENC[AES256_GCM,data:4LeIlZC3xkOlXaiilj+IdOQWI3+jxNvSOYj6AeAAAsq90YW6KDAijrDu22QyaFcRg5sXlr90YcWGiTxTqA85yxjlEG8efDJyAxjN/AV/H+Cg9rrQQOpvIwp9zJQannKcCwmGkkDm4v56dQPy+09e+cD4WdCowFZyyOQiX2rSNzU=,iv:+dNNfzMOmzqYpyvQhv2kFGiu9MPxJs0+Yj4TfB3J0nA=,tag:DFwg57SN+K74dg5mTV6Lig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
