---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bazarr-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        BAZARR__API_KEY: "{{ .BAZARR__API_KEY }}"
        POSTGRES_ENABLED: "true"
        POSTGRES_DATABASE: &dbName bazarr
        POSTGRES_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        POSTGRES_USERNAME: &dbUser "{{ .POSTGRES_USERNAME }}"
        POSTGRES_PASSWORD: &dbPass "{{ .POSTGRES_PASSWORD }}"
        POSTGRES_PORT: "5432"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  data:
    - secretKey: BAZARR__API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 0ca3274a-2f00-4455-aa6e-1df53e0de6dc
        property: token
    - secretKey: POSTGRES_USERNAME
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 0ca3274a-2f00-4455-aa6e-1df53e0de6dc
        property: pg_user
    - secretKey: POSTGRES_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 0ca3274a-2f00-4455-aa6e-1df53e0de6dc
        property: pg_password
    - secretKey: POSTGRES_SUPER_USER
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: username
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: password
