apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:1AnWUTkGR+qwGlPDkGI0hkFw1BkrN4ZSkQc+74z9z43s0K4TI8JQmg==,iv:W+BKdKhAoZKTNVa2a86+4eNbmgRDKe98Y2UIE3wlGJQ=,tag:zHunw0d5tNPr81lQbijfrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age126422qm0mrq0tpmm0rjcacjznz8ggcf2map6yrz3y944e8x4tansxe73l5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRU05CSmlDZzJFaktRamxv
            MGl1TUZBdjIrRmU5dmRIL2tEMnMrMElNOHlNCmVLaWhxWWJ2TXBwZENzKzRXVVg4
            SUFDZ2FXSVR4TVJBdklDV28zYWdYOTAKLS0tIGM0Tkcxd1ZHT092WUNMK2tlV3B4
            QVdTd0lPemRud2Ixeld2TkZ5RXV0UG8KkCCCBHtkBeuyayHx2qwclzDBOQxfe+ru
            dw+MtoHYykNO3BoVR6/ToqF99M/OExN5rOsgCyS9n9WGftTlgW0zUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-30T23:49:51Z"
    mac: ENC[AES256_GCM,data:vGFvc9BeOVErFshO6/N5fh/APvKlDtPpFjm8YIXpWI3Jw71S+uvmZfLoJw3rHiUQ+Z4FgS0ibn7bYStTzwbyekK/X88u0sU2puqKxyf9C0INzF0vu6siyDx9brycpE3DQ/G0fSeyWCybtm1+EJnyrVv4rGc5J2tOsIR4j450/uk=,iv:y+aYZeex9pSZ25Hma/bGiTC7xL+CHXzM7WwEiXhJ2+Q=,tag:0J4/c2CN4zyqGWPjiOWiBw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
