---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: friendica-db-secret
  namespace: selfhosted
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        username: &dbUser "{{ .FRIENDICA__DB_USER }}"
        password: &dbPass "{{ .FRIENDICA__DB_PASS }}"
  data:
    - secretKey: FRIENDICA__DB_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 0e5d8714-665f-4de5-a759-e73b86f52c16
        property: mariadb_user
    - secretKey: FRIENDICA__DB_PASS
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 0e5d8714-665f-4de5-a759-e73b86f52c16
        property: mariadb_password
