---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghostfolio-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        ACCESS_TOKEN_SALT: "{{ .ACCESS_TOKEN_SALT }}"
        JWT_SECRET_KEY: "{{ .JWT_SECRET_KEY }}"
        DATABASE_URL: "postgresql://{{ .DB_USER }}:{{ .DB_PASS }}@postgres16-rw.database.svc.cluster.local:5432/ghostfolio?sslmode=false"
        # Postgres Init
        INIT_POSTGRES_DBNAME: ghostfolio
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .DB_USER }}"
        INIT_POSTGRES_PASS: "{{ .DB_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  data:
    - secretKey: ACCESS_TOKEN_SALT
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 45f4dbf9-3a72-4856-9329-0d0a756064a3
        property: access_token_salt
    - secretKey: JWT_SECRET_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 45f4dbf9-3a72-4856-9329-0d0a756064a3
        property: jwt_token

    - secretKey: DB_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 45f4dbf9-3a72-4856-9329-0d0a756064a3
        property: pg_user
    - secretKey: DB_PASS
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 45f4dbf9-3a72-4856-9329-0d0a756064a3
        property: pg_password

    - secretKey: POSTGRES_SUPER_USER
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: username
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: password
