---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: rainloop
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      main:
        strategy: RollingUpdate

        containers:
          main:
            image:
              repository: wernerfred/docker-rainloop
              tag: 1.17.0
            resources:
              requests:
                cpu: 12m
                memory: 64M
              limits:
                memory: 512M

    service:
      main:
        ports:
          http:
            port: 80

    ingress:
      main:
        enabled: true
        className: "external"
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
        hosts:
          - host: &host "webmail.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      data:
        enabled: true
        existingClaim: rainloop
        globalMounts:
          - path: /rainloop/data
