---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prowlarr-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        PROWLARR__API_KEY: "{{ .PROWLARR__API_KEY }}"
        #PROWLARR__POSTGRES_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        PROWLARR__POSTGRES_HOST: &dbHost sql.${PROD_DOMAIN}
        PROWLARR__POSTGRES_PORT: "5432"
        PROWLARR__POSTGRES_USER: &dbUser "{{ .PROWLARR__POSTGRES_USER }}"
        PROWLARR__POSTGRES_PASSWORD: &dbPass "{{ .PROWLARR__POSTGRES_PASSWORD }}"
        PROWLARR__POSTGRES_MAIN_DB: prowlarr_main
        PROWLARR__POSTGRES_LOG_DB: prowlarr_log
        # Postgres Init
        #INIT_POSTGRES_DBNAME: prowlarr_main prowlarr_log
        #INIT_POSTGRES_HOST: *dbHost
        #INIT_POSTGRES_USER: *dbUser
        #INIT_POSTGRES_PASS: *dbPass
        #INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  data:
    - secretKey: PROWLARR__POSTGRES_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 43e68fd7-3987-4d16-95ea-64505d0748c5
        property: pg_user
    - secretKey: PROWLARR__POSTGRES_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 43e68fd7-3987-4d16-95ea-64505d0748c5
        property: pg_password
    - secretKey: PROWLARR__API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 43e68fd7-3987-4d16-95ea-64505d0748c5
        property: token
    - secretKey: POSTGRES_SUPER_USER
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: username
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: password
