---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reflector
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      chart: reflector
      version: 7.1.216
      sourceRef:
        kind: HelmRepository
        name: reflector
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    replicaCount: 1

    image:
      repository: emberstack/kubernetes-reflector
      tag: ""

    cron:
      enabled: false
      schedule: "*/15 * * * *"
      activeDeadlineSeconds: 600
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000

    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 10
      targetCPUUtilizationPercentage: 80


