---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  labels:
    app.kubernetes.io/name: homepage
data:
  bookmarks.yaml: |
    - Media:
        - YouTube:
            - icon: youtube.png
              href: 'https://youtube.com/feed/subscriptions'
        - Spotify:
            - icon: spotify.png
              href: 'http://open.spotify.com'
    - Infrastructure:
        - Vultr:
            - icon: vultr.png
              href: 'https://my.vultr.com'
    - Git:
        - k8s-at-home:
            - icon: kubernetes-dashboard.png
              href: 'https://nanne.dev/k8s-at-home-search/'
        - homelab-flux:
            - icon: github.png
              href: 'https://github.com/erenfro/homelab-flux'
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
  services.yaml: |
    - Calendar:
        # - Calendar:
        #     widget:
        #       type: calendar
        #       firstDayInWeek: sunday # optional - defaults to monday
        #       view: monthly # optional - possible values monthly, agenda
        #       maxEvents: 10 # optional - defaults to 10
        #       integrations: # optional
        #         - type: sonarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr, lidarr, readarr
        #           service_group: Downloads # group name where widget exists
        #           service_name: Sonarr # service name for that widget
        #         - type: radarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr, lidarr, readarr
        #           service_group: Downloads # group name where widget exists
        #           service_name: Radarr # service name for that widget
        #         - type: readarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr, lidarr, readarr
        #           service_group: Downloads # group name where widget exists
        #           service_name: Readarr # service name for that
        - Agenda:
            widget:
              type: calendar
              view: agenda # optional - possible values monthly, agenda
              maxEvents: 20 # optional - defaults to 10
              integrations: # optional
                - type: sonarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr>
                  service_group: Downloads # group name where widget exists
                  service_name: Sonarr # service name for that widget
                - type: radarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr>
                  service_group: Downloads # group name where widget exists
                  service_name: Radarr # service name for that widget
                - type: readarr # active widget type that is currently enabled on homepage - possible values: radarr, sonar>
                  service_group: Downloads # group name where widget exists
                  service_name: Readarr # service name for that widget
    - Infrastructure:
        - Cloudflared:
            href: https://dash.cloudflare.com/
            icon: cloudflare-zero-trust.png
            description: Cloudflared Tunnel
            widget:
              type: cloudflared
              accountid: {{HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID}}
              tunnelid: {{HOMEPAGE_VAR_CLOUDFLARED_TUNNELID}}
              key: {{HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN}}
  settings.yaml: |
    title: Dashboard
    favicon: https://github.com/walkxcode/dashboard-icons/blob/main/png/heimdall.png
    theme: dark
    color: slate
    headerStyle: clean
    layout:
      Calendar:
        style: column
        icon: mdi-calendar
      Media:
        style: column
        icon: mdi-play-circle
      Infrastructure:
        style: row
        columns: 3
        icon: mdi-server
      Storage:
        style: row
        columns: 2
        icon: mdi-desktop-tower
      Home:
        style: column
        icon: mdi-home-analytics
      Monitoring:
        style: column
        icon: mdi-chart-line
      Downloads:
        style: row
        columns: 3
        icon: mdi-download-circle
    providers:
      longhorn:
        url: http://longhorn-frontend.storage
  widgets.yaml: |
    # - resources:
    #     backend: kubernetes
    #     cpu: true
    #     expanded: true
    #     memory: truehttps://github.com/walkxcode/dashboard-icons/blob/main/png/homepage.png?raw=true
    - logo:
        icon: https://raw.githubusercontent.com/LilDrunkenSmurf/k3s-home-cluster/main/icons/lds-transparent.png
    - search:
        provider: [google]
        focus: false
        target: _blank
    - greeting:
        text_size: xl
        text: "Howdy Hey!"
    - kubernetes:
        cluster:
          cpu: true
          label: cluster
          memory: true
          show: true
          showLabel: true
        nodes:
          cpu: true
          memory: true
          show: false
          showLabel: true
    - openmeteo:
        label: Home
        latitude: ${LATITUDE}
        longitude: ${LONGITUDE}
        units: metric
        cache: 5
    - longhorn:
        expanded: false
        total: true
        labels: true
        nodes: false
    - datetime:
        text_size: l
        format:
          dateStyle: long
          timeStyle: short
          hourCycle: h23
