apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:5gLvVyDx74YhR3KWwJ/3OZlYAuMnwoSqvRwoKj8eVEglbvjvuVEyKQ==,iv:I0/b8d8WZBMW4faho4l7j9sbgzV6mqqliyv4bXxOhbc=,tag:vdFjWLbKNZK4GO6zMQ3i9A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age126422qm0mrq0tpmm0rjcacjznz8ggcf2map6yrz3y944e8x4tansxe73l5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJbml3dUEzdzdzWWtoVXZQ
            ckl1UDQ2S01raXVPKzZlN05nRk1LTGRkWWxnCm9uQ0pTeWd4M0Q2RllTalZNZFpa
            aDhRbDZNVDY1aXlZVlJFYlJXRkJNZHcKLS0tIEZsdGJ1Q3pTR3llZTY3cS93WENE
            VzA0UVhzKzFXMUYvcklBdHhkcVJlb1UKp/nwFpIf/vLXG0QDAUmUiUZEpCkDps+t
            cyf2e22NBSRzL4MXC44ju13r2z3V90rCyy/gLHro8v1Ub71x7ay9DQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-22T02:07:19Z"
    mac: ENC[AES256_GCM,data:bzK9MAl3bSAEwFZnxKRNx6EB3Y3I/TCn3CnNYzjgAhUtoc17K8r0JHOw4kqqow0IsFHJgh8urZ4YD7UonwdpUBg0NZr3O5RYp0c+g+8Zo8XWWmwvtCPvZh+XdN7/tvP70e6uxb+gf/8bcmB3rP17HEvq66kHJztbXjK+zZukHAE=,iv:eLZcZLmrpxoF5BVBm3SwkiDaduiIEWjMEckLNFGw6oc=,tag:Axavg712tZnQuYtBjZP9/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
