---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./homepage/ks.yaml
  - ./linkding/ks.yaml
  #- ./paperless/ks.yaml
  - ./wikijs/ks.yaml
