apiVersion: mariadb.mmontes.io/v1alpha1
kind: Backup
metadata:
  name: mariabackup
spec:
  mariaDbRef:
    name: mariadb
  schedule:
    cron: "0 0 * * *"
  maxRetentionDays: 14
  storage:
    volume:
      nfs:
        server: "${NAS_HOST}"
        path: /volume1/Media/mariadb
      #mountOptions:
      #  - nfsvers=4.0
      #  - nconnect=3
      #  - hard
      #  - noatime
    #storageClassName: mariabackup-nfs
    #persistentVolumeClaim:
    #  resources:
    #    requests:
    #      storage: 100Mi
    #  accessModes:
    #    - ReadWriteOnce
