---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mariadb-secret
  namespace: database
spec:
  target:
    name: mariadb-secret
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        password: "{{ .password }}"
  data:
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 33bcb3ac-c721-4c6c-a0de-1a9ea637fc86
        property: password
