#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: mariabackup
#  namespace: database
#spec:
#  accessModes:
#    - ReadWriteOnce
#  storageClassName: longhorn-database
#  resources:
#    requests:
#      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariabackup
  namespace: database
spec:
  storageClassName: mariabackup
  capacity:
    storage: 1Mi # Size does not matter
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${NAS_HOST}"
    path: /volume1/Media/mariadb
  # Note: The first two options are strictly for NFSv4.2
  mountOptions:
    - nfsvers=4.0
    - nconnect=8
    - hard
    - noatime
