---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarr-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        SONARR__API_KEY: "{{ .SONARR__API_KEY }}"
        SONARR__POSTGRES_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        SONARR__POSTGRES_PORT: "5432"
        SONARR__POSTGRES_USER: &dbUser "{{ .SONARR__POSTGRES_USER }}"
        SONARR__POSTGRES_PASSWORD: &dbPass "{{ .SONARR__POSTGRES_PASSWORD }}"
        SONARR__POSTGRES_MAIN_DB: sonarr_main
        SONARR__POSTGRES_LOG_DB: sonarr_log
        # Postgres Init
        INIT_POSTGRES_DBNAME: sonarr_main sonarr_log
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # Pushover
        PUSHOVER_TOKEN: "{{ .SONARR__PUSHOVER_TOKEN }}"
        PUSHOVER_USER_KEY: "{{ .SONARR__PUSHOVER_USER_KEY }}"
  data:
    - secretKey: SONARR__API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 0297ca08-5770-4ce4-8a03-d1d95003e90b
        property: token
    - secretKey: SONARR__POSTGRES_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 0297ca08-5770-4ce4-8a03-d1d95003e90b
        property: pg_user
    - secretKey: SONARR__POSTGRES_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 0297ca08-5770-4ce4-8a03-d1d95003e90b
        property: pg_password
    - secretKey: POSTGRES_SUPER_USER
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: username
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: password
    - secretKey: SONARR__PUSHOVER_TOKEN
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 4d219e25-625f-4ac3-838b-4191c9721e9c
        property: username
    - secretKey: SONARR__PUSHOVER_USER_KEY
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 4d219e25-625f-4ac3-838b-4191c9721e9c
        property: password
