---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkding-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        LD_DB_ENGINE: postgres
        LD_DB_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        LD_DB_PORT: "5432"
        LD_DB_USER: &dbUser "{{ .LINKDING__POSTGRES_USER }}"
        LD_DB_PASSWORD: &dbPass "{{ .LINKDING__POSTGRES_PASSWORD }}"
        LD_DB_DATABASE: &dbName linkding
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  data:
    - secretKey: LINKDING__POSTGRES_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: bbd835c1-4698-466d-a23f-5e497ebb7a1f
        property: pg_user
    - secretKey: LINKDING__POSTGRES_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: bbd835c1-4698-466d-a23f-5e497ebb7a1f
        property: pg_password
    - secretKey: POSTGRES_SUPER_USER
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: username
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: password
