apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:PMtUjw2TgdnKYqLDDi42+2Io+IrhbY+sYGMMDaJTdD0TV2QZfzBKXWi/9u0wywWQtt9BLQ/FM25lf60i,iv:Bq80BRczzENV4s3vBNveqZcR9+RYXytlaqaBx8g6+gM=,tag:+w9m8EzJxlUtMJZ0St6u/Q==,type:str]
    username: ENC[AES256_GCM,data:FJLsxWw=,iv:g2GW2DLCVak63d+WgspTXyajGTgu2sgdsU9u/ymaSUQ=,tag:xDlXQE3wfSeW41BMlfH0DQ==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age126422qm0mrq0tpmm0rjcacjznz8ggcf2map6yrz3y944e8x4tansxe73l5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBldWVNUm9ueE1NbnhDbnpI
            L1JLNlFVLzBlN2tDUVdDbTdIeWxDNjhJajBBCkxTeVNsQW5sclpqRTNBMkIwL0ND
            ckpvUTlLaGducHlmRVNaQm1EVkNYdTQKLS0tIFJSMXFNcjJJZDg0RlBLb1hic1lz
            ZGRDYjA1SDJCaHQ3VmNIaHJaQmR2Q3MKe1Gx3jvpWyRDTF+M3nfY+EsZNKQ4dYxP
            Puf2Pf1ASajAmkCxEAK5SUyPxeDIGovAbUf4GQXfN2kPbLogqrGTrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-30T23:49:57Z"
    mac: ENC[AES256_GCM,data:ol1C5SSoUdmbitZPThVDdjJEvPcXuvY7bt0FkxfiMeAB+3ztXfOcVOoWhgmn+nof/Lsk5mm56qjdOcJJWz1H5DCvqnhNQ42vxSEDRCfR4gcTR9qMczUOG4wM6ESwcUPhkBfSm/q2N80N6Xg+wbTu/2R05/Fctrsps4wbEBwBRK0=,iv:AzEKBfwr8TtEH6TLRiHVU1K4803hTIxSIp9p6A65Bcc=,tag:bu/5fhhtlZIL0pB01ZtQwQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
