apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:BRJfUqcBYnYpxu3Q1q8rYZAfbVY2ODkVJAOFTwQcbWRtjfWohZvj1rT/mE6+1L43kB71qboNkt3w286+,iv:98FYtDTkTnbcy3weT64IrNpF5HsT0oNGotE3uJm5A2I=,tag:9dK5fLNtb/L3hG4ZAYJtPA==,type:str]
    username: ENC[AES256_GCM,data:0Xiqs74=,iv:PJkuLQf5b32BZueBAILrqipRJIzeAPgXYhT7wmOrRdI=,tag:6nIvpkV8tLlgIuLLdN7ekQ==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age126422qm0mrq0tpmm0rjcacjznz8ggcf2map6yrz3y944e8x4tansxe73l5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3RHQvVElobHdZMHlzd2x1
            MmVxWTAzcklZR2ZXeXdNU0RUbnV2VHNzN0JnCllXTkphbzVBaEU0VU5WdU9wSGJ4
            UHk4dm5CL2tMR0dPcDNhRVBVaFJjbFkKLS0tIDJsbi9JVFIxUnF3M3lrZStZNkVo
            ejFJTkQvYzkwRE4yVWxNYmZTQWFtN2cKpx1YrNr7wVvYuAgrJ0oTA9RgLBWxhHNA
            dubcn+1r1Fq/IiF/5zlQ1B4/gXAdhZtfJahLtJkVm0HKQfdQnuVEUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-28T06:46:37Z"
    mac: ENC[AES256_GCM,data:wSEvWFaMjK6ZuAdNN1DLZmpNhZg3gWR9/ACOqjEoRH3NIClDV8Ad5ac8De+SAIyGQBHQvPu6WX2cnm6hqhFFVV6m//tSJTq3x4V4eXH6HrFEfp3SAfQE/xooJ+UXAxEo6tohMQb1huAa1cYj9ml6tdJXxO8kV2TS1wuck0v+0Kk=,iv:wNAWassW0H3Wf0oe3+ueh+rXePsMJnm5dcw8UkqZGJ8=,tag:OwDr7y6/GxZ/STpQWKslMQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
