---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app external-dns-powerdns
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.13.1
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: *app
    provider: pdns
    sources:
      - service
      - ingress

    env:
      - name: EXTERNAL_DNS_PDNS_API_KEY
        valueFrom:
          secretKeyRef:
            name: external-dns-powerdns-secret
            key: pdns-api-key
      - name: EXTERNAL_DNS_PDNS_API_URL
        valueFrom:
          secretKeyRef:
            name: external-dns-powerdns-secret
            key: pdns-api-url
    policy: sync
    txtOwnerId: default
    txtPrefix: k8s.
    domainFilters:
      - "${SECRET_DOMAIN}"
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: external-dns-bind-secret
