---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: radarr-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        RADARR__API_KEY: "{{ .RADARR__API_KEY }}"
        RADARR__POSTGRES_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        RADARR__POSTGRES_PORT: "5432"
        RADARR__POSTGRES_USER: &dbUser "{{ .RADARR__POSTGRES_USER }}"
        RADARR__POSTGRES_PASSWORD: &dbPass "{{ .RADARR__POSTGRES_PASSWORD }}"
        RADARR__POSTGRES_MAIN_DB: radarr_main
        RADARR__POSTGRES_LOG_DB: radarr_log
        # Postgres Init
        INIT_POSTGRES_DBNAME: radarr_main radarr_log
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # Pushover
        PUSHOVER_TOKEN: "{{ .RADARR__PUSHOVER_TOKEN }}"
        PUSHOVER_USER_KEY: "{{ .RADARR__PUSHOVER_USER_KEY }}"
  data:
    - secretKey: RADARR__API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: a8382e67-3d4f-4cc7-8f84-a391c1fcfad6
        property: token
    - secretKey: RADARR__POSTGRES_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: a8382e67-3d4f-4cc7-8f84-a391c1fcfad6
        property: pg_user
    - secretKey: RADARR__POSTGRES_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: a8382e67-3d4f-4cc7-8f84-a391c1fcfad6
        property: pg_password
    - secretKey: POSTGRES_SUPER_USER
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: username
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: password
    - secretKey: RADARR__PUSHOVER_TOKEN
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 4d219e25-625f-4ac3-838b-4191c9721e9c
        property: username
    - secretKey: RADARR__PUSHOVER_USER_KEY
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 4d219e25-625f-4ac3-838b-4191c9721e9c
        property: password
