---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN/./-}-production"
  namespace: networking
spec:
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "default"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "default"
  secretName: "${SECRET_DOMAIN/./-}-production-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN}"
  dnsNames:
    - "${SECRET_DOMAIN}"
    - "*.${SECRET_DOMAIN}"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN_2/./-}-production"
  namespace: networking
spec:
  secretName: "${SECRET_DOMAIN_2/./-}-production-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN_2}"
  dnsNames:
    - "${SECRET_DOMAIN_2}"
    - "*.${SECRET_DOMAIN_2}"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN_3/./-}-production"
  namespace: networking
spec:
  secretName: "${SECRET_DOMAIN_3/./-}-production-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN_3}"
  dnsNames:
    - "${SECRET_DOMAIN_3}"
    - "*.${SECRET_DOMAIN_3}"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN_4/./-}-production"
  namespace: networking
spec:
  secretName: "${SECRET_DOMAIN_4/./-}-production-tls"
  issuerRef:
    name: zerossl-production
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN_4}"
  dnsNames:
    - "${SECRET_DOMAIN_4}"
    - "*.${SECRET_DOMAIN_4}"
