---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bookstack-db-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        username: "{{ .BOOKSTACK__DB_USER }}"
        password: "{{ .BOOKSTACK__DB_PASS }}"
  data:
    - secretKey: BOOKSTACK__DB_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d78ac4e2-1769-49b7-aac7-afb8caf9d3dc
        property: mariadb_user
    - secretKey: BOOKSTACK__DB_PASS
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d78ac4e2-1769-49b7-aac7-afb8caf9d3dc
        property: mariadb_password
