---
apiVersion: mariadb.mmontes.io/v1alpha1
kind: User
metadata:
  name: bookstack
  namespace: selfhosted
spec:
  mariaDbRef:
    name: mariadb-galera
    namespace: database
  passwordSecretKeyRef:
    name: bookstack-db-secret
    key: password
  maxUserConnections: 20
---
apiVersion: mariadb.mmontes.io/v1alpha1
kind: Database
metadata:
  name: bookstack
  namespace: selfhosted
spec:
  mariaDbRef:
    name: mariadb-galera
    namespace: database
  characterSet: utf8
  collate: utf8_general_ci
---
apiVersion: mariadb.mmontes.io/v1alpha1
kind: Grant
metadata:
  name: bookstack
  namespace: selfhosted
spec:
  mariaDbRef:
    name: mariadb-galera
    namespace: database
  privileges:
    - "SELECT"
    - "INSERT"
    - "UPDATE"
    - "CREATE"
    - "INDEX"
    - "ALTER"
    - "DROP"
    - "TRIGGER"
  database: "bookstack"
  table: "*"
  username: bookstack
  host: "%"
