---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # Pushover
        ALERTMANAGER_PUSHOVER_TOKEN: "{{ .AM__PUSHOVER_TOKEN }}"
        PUSHOVER_USER_KEY: "{{ .AM__PUSHOVER_USER_KEY }}"
  data:
    - secretKey: AM__PUSHOVER_TOKEN
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 30fb1e5e-951c-4c2b-b30a-0af2e38ca5cc
        property: username
    - secretKey: AM__PUSHOVER_USER_KEY
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 30fb1e5e-951c-4c2b-b30a-0af2e38ca5cc
        property: password
