---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  #- ./helmvalues.yaml
  - ./external-secret.yaml
  - ./helmrelease.yaml
  - ./scrapconfigs
  - ./prometheusrules
configMapGenerator:
  - name: alertmanager-config-tpl
    files:
      - alertmanager.yaml=./resources/alertmanager.yaml
generatorOptions:
  disableNameSuffixHash: true
