---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: unpackerr-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        UN_RADARR_0_API_KEY: |-
          {{ .radarr_token }}
        UN_SONARR_0_API_KEY: |-
          {{ .sonarr_token }}
        UN_LIDARR_0_API_KEY: |-
          {{ .lidarr_token }}
        UN_READARR_0_API_KEY: |-
          {{ .readarr_token }}
  data:
    - secretKey: radarr_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: a8382e67-3d4f-4cc7-8f84-a391c1fcfad6
        property: token
    - secretKey: sonarr_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 0297ca08-5770-4ce4-8a03-d1d95003e90b
        property: token
    - secretKey: lidarr_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 1c97df16-2356-4ae4-9186-20bd688c4554
        property: token
    - secretKey: readarr_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 440a1f9d-5760-4100-97a4-48982fab281a
        property: token
