---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-ldap-secrets
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # Authentik
        token: "{{ .AUTHENTIK_LDAP_TOKEN }}"
  data:
    - secretKey: AUTHENTIK_LDAP_TOKEN
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 5c98c9a2-fc81-4dff-91ff-0c1e10d32c9d
        property: ldap_token
