---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app authentik-ldap
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.3.0
      sourceRef:
        name: bjw-s
        kind: HelmRepository
        namespace: flux-system
      interval: 5m
  values:
    global:
      fullnameOverride: *app
    automountServiceAccountToken: false
    controller:
      type: deployment
      replicas: 3
    image:
      repository: ghcr.io/goauthentik/ldap
      tag: "2023.10.4"
    podLabels:
      egress.home.arpa/nginx-external: "allow"
    env:
      TZ: "${TIMEZONE}"
      AUTHENTIK_HOST: "https://authentik.${SECRET_DOMAIN}"
    envFrom:
      - secretRef:
          name: authentik-ldap-secrets
    service:
      main:
        enabled: true
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          coredns.io/hostname: "auth.${SECRET_DOMAIN}"
          io.cilium/lb-ipam-ips: 172.17.1.202
        ports:
          http:
            enabled: false
          ldap-tcp:
            enabled: true
            port: 389
            targetPort: 3389
            protocol: TCP
          ldap-udp:
            enabled: true
            port: 389
            targetPort: 3389
            protocol: UDP
          ldaps-tcp:
            enabled: true
            port: 636
            targetPort: 6636
            protocol: TCP
          ldaps-udp:
            enabled: true
            port: 636
            targetPort: 6636
            protocol: UDP
    podSecurityContext:
      runAsUser: &uid 1000
      runAsGroup: *uid
      fsGroup: *uid
      fsGroupChangePolicy: Always
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        memory: 6000Mi
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: "DoNotSchedule"
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: *app
            app.kubernetes.io/instance: *app
