---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fider-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        DATABASE_URL: "postgres://{{ .FIDER__DB_USER }}:{{ .FIDER__DB_PASS }}@postgres16-rw.database.svc.cluster.local:5432/fider?sslmode=disable"
        JWT_SECRET: "{{ .FIDER__JWT_SECRET }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: fider
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .FIDER__DB_USER }}"
        INIT_POSTGRES_PASS: "{{ .FIDER__DB_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  data:
    - secretKey: FIDER__DB_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 8b595219-e131-467c-8ee4-69fbb4bf51ab
        property: pg_user
    - secretKey: FIDER__DB_PASS
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 8b595219-e131-467c-8ee4-69fbb4bf51ab
        property: pg_password
    - secretKey: FIDER__JWT_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 8b595219-e131-467c-8ee4-69fbb4bf51ab
        property: jwt_secret

    - secretKey: POSTGRES_SUPER_USER
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: username
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: password
