---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: fider
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
              pullPolicy: IfNotPresent
            envFrom: &envFrom
              - secretRef:
                  name: fider-secret
        containers:
          main:
            image:
              repository: getfider/fider
              pullPolicy: IfNotPresent
              tag: 0.21.1
            env:
              TZ: ${TIMEZONE}
              # App
              BASE_URL: https://feedback.${SECRET_DOMAIN}
              EMAIL_NOREPLY: "noreply@${SECRET_DOMAIN}"
              EMAIL_SMTP_HOST: "${MAIL_PROD_SMTP}"
              EMAIL_SMTP_PORT: "${SMTP_PORT}"
            envFrom: *envFrom
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        ports:
          http:
            port: 3000
    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "feedback.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
