---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: kube-vip
spec:
  staticConfigs:
    - targets:
        - 172.17.1.51:2112
        - 172.17.1.52:2112
        - 172.17.1.53:2112
  metricsPath: /metrics
