apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:B/EQSeT6svCb43X6zAw+9lrXdNQjibI=,iv:IsT/PnCDjJChunCMkH4PfOQFER2znxJR22YzGgHvvls=,tag:Wve5W07M5o5gtF3ya0xSoQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:uY0nOlz1Yqm2NNY0La7QUuFwHfdnJM62tN42ceWXdE+KM+uH,iv:X+lUuaVn16aUnvLyGZQ3Rb1yoLzhFiS/MCsokQkOUuQ=,tag:221C2mT9k37xzQp9y63bGw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:GLiDyd65eZJMFaSOJwp0TYI=,iv:HcGZbc8Etqkp8EIXZaddLvwngLclkF1hssytS+jcnSo=,tag:HAvqKsB6sRCb8xrvFMjMIw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age126422qm0mrq0tpmm0rjcacjznz8ggcf2map6yrz3y944e8x4tansxe73l5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ZFV2UCsxM21nVkc5WlZn
            VmtyTmxlQ2RBN1BLUzhQOVlsTzZSaHJXaFdZClZiOEErcFBwKzJBUjI5bHpFL3dD
            NUFvTEdhZEFDR1FhZXNjQU1TZ215aE0KLS0tIGxrSmVZMHRPMVdjTVBKLzlMTFBH
            R2d4bGhtbmNNSkd1Y3JzZEo1V1ZGajQK3yERwj8ql4oLBKRFQJVKNG8cg99SQu2V
            dlZrcP0sSlYpIETrMQ6cBLsXFuiUEg1DRKRRcdKteEFmRJxmfsGFfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-20T22:05:14Z"
    mac: ENC[AES256_GCM,data:cehvvx68YVCWcX96lI1raMyZZ79ixJIy3dAUF5fTX1I/KSCj75dJ+XuMgXNJK5aR7BToJ9vcDSB450f9k4hrTtqUWuYib9UqiG+/lK1Y8BP6+GABxY9teiNcM9FMNU0E00pxwwyd1yASputuhvkvfNcQ78EraiOTQ64abn53vAw=,iv:De+3r24YBCKpdIbBe2vHawbV90tvpTFzRvnju7CJs+4=,tag:aMny/ynJ4AmXfCpkwqQJ7A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
