---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Toronto"
  COREDNS_ADDR: "10.43.0.10"
  KUBE_VIP_ADDR: "172.17.51.254"
  CLUSTER_CIDR: "10.42.0.0/16"
  SERVICE_CIDR: "10.43.0.0/16"
  NODE_CIDR: "172.17.0.0/16"
  ASN_ROUTER: "64512"
  IP_ROUTER: "172.17.0.1"
  IP_LB_CIDR: "172.18.254.0/24"