apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:UcysiDZXfyx6S4ye,iv:Spxx3ZXDYoLBhIOLLQWWzLOgUSIKxRu3F2hhpjOF3oc=,tag:Qv5SU4VO0ZJiDbVe4NhUyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age126422qm0mrq0tpmm0rjcacjznz8ggcf2map6yrz3y944e8x4tansxe73l5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSWFzRFpqYkhEQ3FzYlVW
            RWdiY2JCM3VLaGR5WmJLSFkySlkxZ3RTdDBNCmVtTUdxUjdxU3ZHU1JLTTIrR0hT
            T3kwRkhyTi9RdnFIMEtkRjJzUysycGcKLS0tIHVsMzhydXZNM3g5Qm1OazRzclJ3
            TmsxTE0rbmh4ZHpQdWZHSzVpdXVUcTQKulgs5p7PUDzA8CBjyefq2R4PwEZyHvPH
            gVQWYnB7T2i24PDbgZTeIwqCVm0U93IMahtXosk2xShapw6qPYVDwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-20T22:05:13Z"
    mac: ENC[AES256_GCM,data:7dQns0DBkbIiNmXGvci7/ucU7G5vuh3gFEmWaqPxiVA+Y3/VHTBSoRWrpTE7b/xdDYrwlXRI72Aldo5wwtOQcoAIZcBbZWEC4s9XSt/ELcILSDQeqz6kkHeLP/c47A2ONAbldVGbc3KksZTDkQ4nJdxZCTVtavf0K/YoCrQK3Wg=,iv:ONPVgZptXKLrluVHiQ/QgEbO/0EXEGZaFtVEUC9lFYs=,tag:DoHv5KJUDdcz04bxeoNOaA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
