apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:lAeGAvp63omU5rko,iv:hHQoK3UQzAbwwJvbwTACkm6wEGDpZIMAGQo29dDSmss=,tag:tE99rIrycYjZLD4WxsqnsQ==,type:str]
    LDAP_URL: ENC[AES256_GCM,data:QSzkuZnJ/5co9M5oGTVb5q79oI/oZv22/dXK9dW6T8YfbmTf+2Emqw/XxqgeCJq/,iv:VraqNF6FR1bjCqSDEYfsN677T8u8a6Dw7AH4Gh+phwg=,tag:uHUt6izULtmBZO/bl7gCwg==,type:str]
    #ENC[AES256_GCM,data:F//rZw7I+Ql20xOecDFcu07ULGXor0MB2q5wJAP37JlCfllkEq46,iv:YVyBdSCDHnLZtENANJ0wMXsu2fmPgdG6AiDXwdtZniQ=,tag:LoSgKNUuYvAgIPr1cBHkjA==,type:comment]
    LDAP_BASE_DN: ENC[AES256_GCM,data:R7jj9NPjKMpfhmRG3Q==,iv:poy9x4WZqqJXtAb3oDzyQwU7uVJPgqpw2jf6BaE4g8s=,tag:rNC7uqMFJctKtgpUT3X0DQ==,type:str]
    LDAP_READONLY_USER_BIND: ENC[AES256_GCM,data:V6PjopyEV9kINLnF/gsN/GzlRbu6RqbfMwN3rIlEIf9kDg==,iv:qIozXhkUYeXDRgFG59269EWZLVNOFUrFEisjLqppwjY=,tag:XY1pGk0d+oAwe9Rsph821w==,type:str]
    LDAP_READONLY_USER_PASSWORD: ENC[AES256_GCM,data:aNagMM8KyoM8g25WNkSXB1cUaclzZvJg1PsUPUKTWhIzCtPL3O+xPVtEI801LjUJISKTgaVIdbCVdk1h,iv:n9eSDg65uveRiAbWdBR81Y2OL7QMuoA2j4qdbPXsfzk=,tag:y13ZZAnEl7zge+QAvs3dBQ==,type:str]
    NAS_HOST: ENC[AES256_GCM,data:I1U1GQM51sluwjhi,iv:SKpFPhu2Zhzph5EJGf3qCx3Y/70PMnNU76EP7VMpPUk=,tag:xLmlbnxFLdm6jk6uBG/dtw==,type:str]
    NAS_MOUNT_PGBACKUP: ENC[AES256_GCM,data:PMSNwYnIaXrVyPj4Ce74n50VO63B,iv:MTLiAGhZlMNLcVuQmQWTrqX1O2kGyGXDB9qMK7yzr6g=,tag:BetnPieKqDYcwLhDThhQ7w==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:z+ak7cAt92QY0g9qwQ==,iv:kNopOLBL44atY20UV6Hs23CzKP9xDKHNpnQgJ+0Rz44=,tag:gCguX8xUZEdrlIdxDiK9ug==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:M9w=,iv:IuAvco5Nr84BN9zqGTf/n/4hWICO+joJAijisdEQxxU=,tag:hXj0t5loWnnx509j9yOQRg==,type:str]
    SMTP_AUTH_STRATEGY: ENC[AES256_GCM,data:512eLg==,iv:o5XXvcpUhXhBGvqL6bQwIGIlDcYKlZdfGGWs4F6ut4Y=,tag:eIODyjCXGhGor95k/we6HA==,type:str]
    MAIL_PROD_SMTP: ENC[AES256_GCM,data:lQRPsmeCEM6HukuKVMLVmcylPA==,iv:lbyQCLVObT/EzSDj5hppvMSY5RjDQMAOa9yvzEV/oX8=,tag:AZH8ChsHgAnpd4rmXOjv+Q==,type:str]
    MAIL_PROD_IMAP: ENC[AES256_GCM,data:fnKyJVMbYxO43+KbRgXhaTUNUA==,iv:BbPKOFjn5Vd8qqKnTNXAlKOUdoYDHG/Zf/g4P2cdrho=,tag:rtQQBUiWlXrS/BG8iJPdTg==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:dQTQ9/lUpnTwm8ebIqD46c99oHK9g/t/ct6RyTKbQJM=,iv:+R/nJLbk0I3LVhwav/UW3TPZuUDJjX1G3wo1xtCWEiM=,tag:oQNy/EyANRxnXX69WGL6AQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age126422qm0mrq0tpmm0rjcacjznz8ggcf2map6yrz3y944e8x4tansxe73l5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6KytFVUtLdW15eVRpdytJ
            NHIwZVhDQTl6MngwK1JZNU9UcG9hNCtzbUhRCkdvM2JwYmpoeTRBTy9yRFQ5MHdl
            RnZkeHhHR2xNVGs5MFF6ZERLVHVCS2cKLS0tIHBWWmZGdnNibUNQMDhNWjF4UGdJ
            dmszV1VVZTdRSTdPTlc0aTRzSzFjMUkK5rvVFKAeZRZi3vAN5Va2AlGTn/1g72se
            WroTfwwcFwwGP5MTIkQXgjS2daiy4vEJ/jEmvewW0MaV3WTThyU6ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-13T06:41:24Z"
    mac: ENC[AES256_GCM,data:956GTMOmt4Fow4QFpadc95HAMrRlLm92+HOMcKtj2jWeasi/sMIku5r7BQKk9KkEsV3mqadUUDh7URAaQO6QbtHC6biwKehRYYy9KQSZPCACmNu6PxeIEheFngOz1EIPbw0+eIYiJZY0myHQRXPIJxqt5M4yf9rsBuy/CKhncow=,iv:o5IAaV5kthwCCXiW0KV5771NniPb1DTsS45a116q1g4=,tag:M66PTyu2f/2SVjGpBAE3Tg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
