apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:lAeGAvp63omU5rko,iv:hHQoK3UQzAbwwJvbwTACkm6wEGDpZIMAGQo29dDSmss=,tag:tE99rIrycYjZLD4WxsqnsQ==,type:str]
    #ENC[AES256_GCM,data:8E5FC/ubsy+v130baQXj0mvr8OCz/bhIxxhfrqP982O59ZvW2ZLXUy++2fxxZqPmNw==,iv:OoXsd2Lg+t+J29MJ8CMamto2ZMxuMUrai9K4A00yvVI=,tag:yor3cKgHr2kOSB7/wkDP8w==,type:comment]
    LDAP_URL: ENC[AES256_GCM,data:PpFfxb9+P1IsLUXArKK12ESckDrjlJVIBcf3rZc=,iv:VOkhWDKjq7mb5b3oglglUzkUpdTQT3xWndy6uQ1rhxM=,tag:hjLMKWTwJyrgCs0QA7nJEQ==,type:str]
    LDAP_BASE_DN: ENC[AES256_GCM,data:zwZHx+6Nw81M5/QX2ki1Nd2MvCIie+g=,iv:9GBkczS6qxVszQu5t0AiP428Gr47v53oghZVIU0I+dQ=,tag:TewH6Ly11sIjWNt8a7EQgQ==,type:str]
    LDAP_READONLY_USER_BIND: ENC[AES256_GCM,data:BB8CDbPl2gSYp7MrjE15XPH6bWrhoU2IzQ8wA4NDrW8Yatn9,iv:EeHhNEY8TKqEyHr7AKVfkg6Uwnm/I5VGvijlr3juX44=,tag:XOklFFTzf1lTHxoaDIkK4A==,type:str]
    LDAP_READONLY_USER_PASSWORD: ENC[AES256_GCM,data:W8r6p3n4j649Z983E/Mejfgrc7tWvOEi3OE0umDwRd6C,iv:xkqVDBjPJfdcglyJQSmR9RiHoSrt+OaZ9GOoE6w/8yg=,tag:0y1TOncYcxgy2ulG2XadgA==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:z+ak7cAt92QY0g9qwQ==,iv:kNopOLBL44atY20UV6Hs23CzKP9xDKHNpnQgJ+0Rz44=,tag:gCguX8xUZEdrlIdxDiK9ug==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:M9w=,iv:IuAvco5Nr84BN9zqGTf/n/4hWICO+joJAijisdEQxxU=,tag:hXj0t5loWnnx509j9yOQRg==,type:str]
    SMTP_AUTH_STRATEGY: ENC[AES256_GCM,data:512eLg==,iv:o5XXvcpUhXhBGvqL6bQwIGIlDcYKlZdfGGWs4F6ut4Y=,tag:eIODyjCXGhGor95k/we6HA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age126422qm0mrq0tpmm0rjcacjznz8ggcf2map6yrz3y944e8x4tansxe73l5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6KytFVUtLdW15eVRpdytJ
            NHIwZVhDQTl6MngwK1JZNU9UcG9hNCtzbUhRCkdvM2JwYmpoeTRBTy9yRFQ5MHdl
            RnZkeHhHR2xNVGs5MFF6ZERLVHVCS2cKLS0tIHBWWmZGdnNibUNQMDhNWjF4UGdJ
            dmszV1VVZTdRSTdPTlc0aTRzSzFjMUkK5rvVFKAeZRZi3vAN5Va2AlGTn/1g72se
            WroTfwwcFwwGP5MTIkQXgjS2daiy4vEJ/jEmvewW0MaV3WTThyU6ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-02T19:20:48Z"
    mac: ENC[AES256_GCM,data:XkHEgPCFmAj2X+VfvQQJB6ICryN+x30E+5OFp55554V3U6dr3jmQBIEKJ4DbWz8wwkEhAghPT2B9e9bubPS+eWbeCGU1ZZxA7BJb/4vXP9hjm53bFYoMaKexs2V9M36Kz8TxNlH3Ojft/jn5JEaZQfK43akLMtz7tR0ilP+MDqQ=,iv:tarDGM9ubLJ8BW4KAyEWvsOrB0IDG3oLsRIOyZTZ8Tg=,tag:bx/reL8fzfRc5UgssZ04QQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
