apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:efBtboW9tbDCswHXwd2H3jC1/MyVmTE=,iv:61jU//cxz24gdZ5aLMFMqELoCp9o2MRqUwnBcnAxfd4=,tag:bUR0EpmcHll7ETMcFsV+Xg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:ibe0zgCzDnnnJLe8Uy9wI52pFrbWnHdM+7tnTQ09rJVZ0Znw,iv:s/EemVlSe484ZUWizyHMmAkFf0ZVVKxDlpJAaKoDvUg=,tag:lSxcbqMz8LVNEK87Aj9JFQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:P72p48Yvd5DFbqZKezENDn0=,iv:DSHYKc0MGG5XQm7g3dsyeeylWDp1IfEzjQDPupCIq8U=,tag:6PMUh1lzMTpZSij3M4g5pA==,type:str]
    SECRET_BASE_DN: ENC[AES256_GCM,data:wXK3yvl+1sobxI+KTw==,iv:pdLqFjOKLQQdOqImejrA7qpu5uK/lnC6SOmjPaRvJyA=,tag:X34xBG3XcKEW2mUTqjEqAg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age126422qm0mrq0tpmm0rjcacjznz8ggcf2map6yrz3y944e8x4tansxe73l5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTWJwaE5KQUhDcnpZRURm
            N1dVOWNvZU1Pd0phcndSR2JIbURHcTVWUFQwCk1lK2RaY1ZlNW93MDY3VVd0RjI5
            MjRGakVOYkdXQzVuNmMrTGJVbFJNOE0KLS0tIHdaOGVIc2s0KzdnSEQzK2dRcXcx
            SHJxSksyQ0ttUzM2UE5rTG9weDNSRW8KdAMOXoSFO3oHELG0Ru5mQnXbIncJnGH9
            cJsH9ntKqsaV86Y3F7IJoYDDKwHFaoX63CyGrWTw56eKDtK9jWJ5Nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-01T18:54:37Z"
    mac: ENC[AES256_GCM,data:4A1CnmMXTXLdrGsRuEVGKcJggO9Ewk2Ltx3hkGfskgQd8KCBQjLOhEqYSkO4+8hUCotB52zXXli1ZkjTweZzwU+rdap8waLqTJAV09aNPxjo2gxB+ti2awX/vfKGKvCfZDKaCuAy6HHl2eVU2rnbvNU78Rt9EBUv4JXq/uU0Mm0=,iv:NSroLUveSiWTfvW/lvQULkWwnDTA9NfR1A5QwiiicgY=,tag:1MKnfv9YZeZCcUc9hbiOJw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
