apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:efBtboW9tbDCswHXwd2H3jC1/MyVmTE=,iv:61jU//cxz24gdZ5aLMFMqELoCp9o2MRqUwnBcnAxfd4=,tag:bUR0EpmcHll7ETMcFsV+Xg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:ibe0zgCzDnnnJLe8Uy9wI52pFrbWnHdM+7tnTQ09rJVZ0Znw,iv:s/EemVlSe484ZUWizyHMmAkFf0ZVVKxDlpJAaKoDvUg=,tag:lSxcbqMz8LVNEK87Aj9JFQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:P72p48Yvd5DFbqZKezENDn0=,iv:DSHYKc0MGG5XQm7g3dsyeeylWDp1IfEzjQDPupCIq8U=,tag:6PMUh1lzMTpZSij3M4g5pA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age126422qm0mrq0tpmm0rjcacjznz8ggcf2map6yrz3y944e8x4tansxe73l5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTWJwaE5KQUhDcnpZRURm
            N1dVOWNvZU1Pd0phcndSR2JIbURHcTVWUFQwCk1lK2RaY1ZlNW93MDY3VVd0RjI5
            MjRGakVOYkdXQzVuNmMrTGJVbFJNOE0KLS0tIHdaOGVIc2s0KzdnSEQzK2dRcXcx
            SHJxSksyQ0ttUzM2UE5rTG9weDNSRW8KdAMOXoSFO3oHELG0Ru5mQnXbIncJnGH9
            cJsH9ntKqsaV86Y3F7IJoYDDKwHFaoX63CyGrWTw56eKDtK9jWJ5Nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-30T23:49:52Z"
    mac: ENC[AES256_GCM,data:pNhGA1FS9rGXdniOUJ8q6oAaa5OwzDxpYPq1fsiDSpu6E02/psrB21ZrXQybJtRFkeXYLFYkc/76Dw/gul7nI3BjRYGcRRPW10hGeenOLHvceYpKowCkCoRZjX88ayZuzMtPHAF9APQza3SeRemdVrsV1JwPHEGjUPeNe92EH5s=,iv:ehS1Hv02Y+/L2vvCWNiNP83Khwj/pf3oW3xRSu95tNc=,tag:5puDRbn28GkBJ3MBdWJZyQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
