---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings-user
  namespace: flux-system
data:
  SETTINGS_PLACEHOLDER: "settings-value"
  ASN_ROUTER: "64512"
  IP_ROUTER: "172.17.0.1"
  IP_LB_CIDR: "172.17.8.0/24"
