apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    namespace: database
    labels:
        cnpg.io/reload: "true"
stringData:
    username: ENC[AES256_GCM,data:50/1DXbnMvA=,iv:zJM3BW/KlMSoOH+p2wDhfklfxyNun6TlH53eWLR4Eoc=,tag:+tJMrHfGXV86acG5NxjXnw==,type:str]
    password: ENC[AES256_GCM,data:zlHvuKa4,iv:X9O3Qzp4u0KCN8LLG9ElQubs6fRiBvrxwiG9DAn+sx0=,tag:nOVSsqbWZSgxnd+r3S4hEA==,type:str]
    aws-access-key-id: ENC[AES256_GCM,data:sjc5QxfhICdmEXP0CJWmjA==,iv:LXkbSuVKuh/HAyFfhjV4MLhhL/vGjFL2hX01T2y+AK0=,tag:/JfgPpAU3OQN7B7eGQqT4g==,type:str]
    aws-secret-access-key: ENC[AES256_GCM,data:fBtH6yCdxR17mKThuvkxzX1UZGSFXYwyp/G83aotIww=,iv:upawFUegBNMOZWSSqKtWS9jrAJeNA6WWm6nZfbjm6NE=,tag:x8/jkp2tAKn+NUGUkjMmOA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age126422qm0mrq0tpmm0rjcacjznz8ggcf2map6yrz3y944e8x4tansxe73l5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjOXZsQXVxUnVkR3hBYWRK
            OEptaVlWc25yZWxEaGR3eVlDVHZaUUkzVlM4CnN5WUdzTU0yMkl3bUE0UWkrSktO
            K01QSzBWaUhqbHE1OTVuRHJJMXNkc00KLS0tIGJpYURKN0N5azZJWG1vbkViWDYx
            dXBxNTlxQ01ON0tsVDl5d2hQVzNQdlkKU7LqQ/irNaz7baNtSdtBiSkUiHb9mHD+
            CAzq+kviIxvXaZ1NtOkous1P5OXvHUVSA5O5XSs2yVcrNjaAj8/00Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-25T00:07:56Z"
    mac: ENC[AES256_GCM,data:faD3VQ8EEx6AagCFoRi6phjOOMOT45x+IWfTsbIbnkIrF5Y0BFgg14bt6dLnwb+bQiOC3R9CvCvSQ3MuPa/rwobDxkZtTg6b7YSF6rDUPO0mb6/W7QPnrCjpNFj0UETWMqIJl6Hjtu9hmDPuTe/3jZNDCzJTG1RZP5G7l2kjMF8=,iv:FoI6vrfC5Av3FVXuFbtQRD/1khu2dS2nFPhrIneLuZQ=,tag:MOc5Q3VhWXYYijZ5rdYLkg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
