---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        BUCKET_HOST: "{{ .BUCKET_HOST }}"
        BUCKET_NAME: "loki"
        BUCKET_REGION: "ca-east-1"
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
  data:
    - secretKey: BUCKET_HOST
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: ff03e89c-0178-4a00-b7b9-1b50d00fd1e7
        property: bucket_host
    - secretKey: AWS_ACCESS_KEY_ID
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: ff03e89c-0178-4a00-b7b9-1b50d00fd1e7
        property: username
    - secretKey: AWS_SECRET_ACCESS_KEY
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: ff03e89c-0178-4a00-b7b9-1b50d00fd1e7
        property: password
