---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: thanos-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      type: Opaque
      data:
        s3-bucket: thanos
        s3-region: ca-east-1
        s3-endpoint: "{{ .endpoint }}"
        access-key: "{{ .access_key }}"
        secret-key: "{{ .secret_key }}"
  data:
    - secretKey: access_key
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 9c065994-af64-4ea8-b95d-9dddac75ddcf
        property: username
    - secretKey: secret_key
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 9c065994-af64-4ea8-b95d-9dddac75ddcf
        property: password
    - secretKey: endpoint
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: c9cefb83-f535-4d28-965e-523667932959
        property: endpoint_bare
