---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: thanos
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: thanos
      version: 12.20.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: local-path-provisioner
      namespace: kube-system
  values:
    image:
      registry: quay.io
      repository: thanos/thanos
      tag: v0.33.0
    objstoreConfig:
      type: s3
      config:
        insecure: true
    queryFrontend:
      enabled: true
      replicaCount: 2
      #resources:
      #  limits:
      #    memory: 1Gi
      ingress:
        enabled: true
        ingressClassName: internal
        hostname: &host thanos-query-frontend.${SECRET_DOMAIN}
        tls: true
        extraTls:
          - hosts:
              - *host
    query:
      enabled: true
      replicaCount: 2
      replicaLabel: ["__replica__"]
      dnsDiscovery:
        sidecarsService: kube-prometheus-stack-thanos-discovery
        sidecarsNamespace: monitoring
    bucketweb:
      enabled: true
      replicaCount: 2
      #resources:
      #  limits:
      #    memory: 1Gi
    compactor:
      enabled: true
      #resources:
      #  limits:
      #    memory: 1Gi
      extraFlags:
        - --compact.concurrency=4
        - --delete-delay=30m
      retentionResolutionRaw: 14d
      retentionResolution5m: 14d
      retentionResolution1h: 14d
      persistence:
        enabled: true
        storageClass: local-path
        size: 10Gi
    storegateway:
      enabled: true
      #resources:
      #  limits:
      #    memory: 8Gi
      replicaCount: 2
      persistence:
        enabled: true
        storageClass: local-path
        size: 10Gi
    ruler:
      enabled: true
      replicaCount: 2
      #resources:
      #  limits:
      #    memory: 250Mi
      replicaLabel: __replica__
      alertmanagers: ["http://alertmanager-operated.monitoring.svc.cluster.local:9093"]
      extraFlags: ["--web.prefix-header=X-Forwarded-Prefix"]
      config: |-
        groups:
          - name: PrometheusWatcher
            rules:
              - alert: PrometheusDown
                annotations:
                  summary: A Prometheus has disappeared from Prometheus target discovery
                expr: absent(up{job="kube-prometheus-stack-prometheus"})
                for: 5m
                labels:
                  severity: critical
      persistence:
        enabled: true
        storageClass: local-path
        size: 10Gi
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  valuesFrom:
    - kind: Secret
      name: thanos-secret
      valuesKey: s3-bucket
      targetPath: objstoreConfig.config.bucket
    - kind: Secret
      name: thanos-secret
      valuesKey: s3-endpoint
      targetPath: objstoreConfig.config.endpoint
    - kind: Secret
      name: thanos-secret
      valuesKey: s3-region
      targetPath: objstoreConfig.config.region
    - kind: Secret
      name: thanos-secret
      valuesKey: access-key
      targetPath: objstoreConfig.config.access_key
    - kind: Secret
      name: thanos-secret
      valuesKey: secret-key
      targetPath: objstoreConfig.config.secret_key

