---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hedgedoc-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        CMD_SESSION_SECRET: "{{ .HEDGEDOC__SESSION_SECRET }}"
        CMD_DB_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        CMD_DB_PORT: "5432"
        CMD_DB_DIALECT: postgres
        CMD_DB_DATABASE: &dbName hedgedoc
        CMD_DB_USERNAME: &dbUser "{{ .HEDGEDOC__POSTGRES_USER }}"
        CMD_DB_PASSWORD: &dbPass "{{ .HEDGEDOC__POSTGRES_PASSWORD }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  data:
    - secretKey: HEDGEDOC__SESSION_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 8298fbc6-4853-46c9-9844-e6daf62310dd
        property: session_token
    - secretKey: HEDGEDOC__POSTGRES_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 8298fbc6-4853-46c9-9844-e6daf62310dd
        property: pg_user
    - secretKey: HEDGEDOC__POSTGRES_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 8298fbc6-4853-46c9-9844-e6daf62310dd
        property: pg_password
    - secretKey: POSTGRES_SUPER_USER
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: username
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: password
