---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hedgedoc
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.3.0
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 15.5
              pullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: &secret hedgedoc-secret
        containers:
          main:
            image:
              repository: quay.io/hedgedoc/hedgedoc
              pullPolicy: IfNotPresent
              tag: 1.9.9
            env:
              TZ: ${TIMEZONE}
              PUID: 1000
              PGID: 1000
              CMD_DB_DIALECT: postgres
              # toggle to allow more user registering
              # use ldap user instead, with group hedgedoc
              CMD_EMAIL: false
              CMD_ALLOW_EMAIL_REGISTER: false
              CMD_DOMAIN: md.${SECRET_DOMAIN}
              CMD_PROTOCOL_USESSL: true
              CMD_URL_ADDPORT: false
            envFrom:
              - configMapRef:
                  name: hedgedoc-ldap-configmap
              - secretRef:
                  name: *secret
    service:
      main:
        ports:
          http:
            port: 3000
    ingress:
      main:
        enabled: true
        className: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
        hosts:
          - host: &host "md.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
