apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:IKgLEa2lwCVjSO6OBGYeqSownnvJDiA6BmctOFCVr3L8bwQO,iv:UE0NW9wunh7vNjC2dsZaQM84aUCaP/tVhNfwk88Sycc=,tag:LUEp8vSejyphqWoZ4S/gKw==,type:str]
    credentials.json: ENC[AES256_GCM,data:nuAm4rV1sMpZC7X4I2siU7lGdD3XVXfux0vr4akWBiC1hdmgX1jAE+BXSzG9NwRAwJKd2G6hqZJX9swvt/iDLJEWip+NUPBPunaQXq3TZM3+j5MduiGj1XxmGDO+ZAUWAHc02rebPv7d0fw8Uv6sd80L+EjnNVdjCirRzOKWL8ff4fXAB9sCG3d/hGUrCeMTod+XwTAKkfW/3cnI6lV8hfOR/amOC7B7Xpmzc5cmlg==,iv:Dcri35BXlE28oxdvWwhVzsCUHaJU/cgr6kYdNa2wavk=,tag:TpfQkavGhvSffxiZcuEygw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age126422qm0mrq0tpmm0rjcacjznz8ggcf2map6yrz3y944e8x4tansxe73l5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQOWxFZjdWcWFkdnhWcUwz
            QmhvU3c4cmE2YktxeUhZNGFjRWthMUNWOHgwClBEUGJkQkVFSlFuc0NjanVMZmFP
            VGVDN2tHTDNiSmJKbktncDIvY0tUUFkKLS0tIEU0cXhRQzhmWmxRWTdHYzhWcG85
            STNNZG8zcGs4TEZSK3E4TmR4dm8rbkkKhpZ8jDMErLB1NO9/UBPs6dVQ1hfqeEcq
            MKLMeoevL7BjsDd3WdGlrNZ6G+uzxTYtbPbahLRNhIJVKRKxql7nRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-21T23:38:01Z"
    mac: ENC[AES256_GCM,data:9QI537aYo5XT8o6awtNoW8bg1SyjdCNRB2/L7n8buDYxKifS04RhuRB5NG7lzT81vzRolbbmDa/8yhK9B0gO7CaYMeJDIYaFA+TgwD1UAhJNMEoU3NZ6B0IcfT5SDKp2HewD80Jbw6409vg9rirhhOJovBCCkIImSx1A7H3+g6s=,iv:1L5J333lx9NyxuBABcpIlSrDne3aaTCU5OVL1ge352E=,tag:Pwr1JOttSM37mfFj3tREGw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
