apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:IFP7dGc00+JKRIlS1q49J6oiYSHXlbQNGDTp4af8RJZu/2vd,iv:yXCVQlzU9PUNctKB3fK1PxI6GmQB8OMppwzweWSjeRs=,tag:HV1Gjcuy/i7Gh7s9SKynXg==,type:str]
    credentials.json: ENC[AES256_GCM,data:I5PIoWIYYFGhDWLcn1wBWTWSVq9I9YHRztNOox8uqYqdUW8S8YyKCxx1p7y/4kM7AO+uhDt6+32AYjU/ZIWxHvSJxGU1NoS38nJWEE2LEPtdv5qG1qzqdgIUZ5vl5/WGO+1fx60LVMYS4v4AVu8mLS9O4QugkTC0V3Rw0I9vXoCm3TzNbx38aIfS/IpG2ggvU6J5O34nXqlJVlclZJA0J7I9vWHlUcSFcTMOBRcXRw==,iv:dTUtGif4DZoj9ZsWMxKLG5PpriAPZoFPrRWxMuM2fyk=,tag:zqYWsUmvUiEzTPITcrXL7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age126422qm0mrq0tpmm0rjcacjznz8ggcf2map6yrz3y944e8x4tansxe73l5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5MURMMHNOQXZucWpORGRm
            NnJ3OFBRa01WYjFYODJaQzcrU2VvY1N3U3lrCkl6T2dZcG5FRVdaU2F4WWFUUnhI
            YXB6SFEvYWNnRmUyV09BMXQ0aGNLYzQKLS0tIEVvYzZHajF6TEhoUHVjeC9zV0Vk
            S1dXVzRQUTlzbGxFcVhjb2FqRFhUNTgKbnR4IGdxcx9Dd42zkBq6UWIykmfAXNuU
            82WuUWnb4hllLzrkAmDTCg8JcYnofmXwtHH4HPqn732eVRrlVpQJZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-28T06:46:31Z"
    mac: ENC[AES256_GCM,data:lx71msE+KXrXrxcTmYw3RL5d/6qvh7TSgAdGBPv9t6YnDYfo9Afik8IFW9229egokpxOrEZOOYiJKlYjsJF2i7ORwXTdhFuV/hyJTaJjPzMuJioMNBxOVOffeW9LznXynYPqNgU2m5MnmzlZZxiG/Whh8In76ZrjLZDsEGd5TYQ=,iv:Vwrm8Vvh4ic2lsc1wOoUUlg7qwpNiwW7wlpiOTfKuC0=,tag:JUn+6Uso3U0IavfvJRtSIA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
