---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mealie
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.3.0
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: longhorn
      namespace: storage
    - name: volsync
      namespace: volsync
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 15
              pullPolicy: IfNotPresent
            envFrom: &envFrom
              - secretRef:
                  name: mealie-secret
        containers:
          main:
            image:
              repository: docker.io/hkotel/mealie
              tag: frontend-nightly
            env:
              TZ: "${TIMEZONE}"
              # API_URL: "http://mealie-api.default.svc.cluster.local:9000"
              # Light Mode Config
              THEME_LIGHT_PRIMARY: "#005AE6"
              THEME_LIGHT_ACCENT: "#FEBF00"
              THEME_LIGHT_SECONDARY: "#0DFC9D"
              THEME_LIGHT_SUCCESS: "#43A047"
              THEME_LIGHT_INFO: "#1976D2"
              THEME_LIGHT_WARNING: "#FF6D00"
              THEME_LIGHT_ERROR: "#EF5350"
              # Dark Mode Config
              THEME_DARK_PRIMARY: "#0097A7"
              THEME_DARK_ACCENT: "#007A99"
              THEME_DARK_SECONDARY: "#4ba3c7"
              THEME_DARK_SUCCESS: "#43A047"
              THEME_DARK_INFO: "#1976D2"
              THEME_DARK_WARNING: "#FF6D00"
              THEME_DARK_ERROR: "#EF5350"
            envFrom:
              - secretRef:
                  name: mealie-secret
          api:
            image:
              repository: docker.io/hkotel/mealie
              tag: api-nightly
            env:
              TZ: "${TIMEZONE}"
              API_PORT: &api_port 9000
              TOKEN_TIME: 720 # 24 hours * 30 days
              BASE_URL: &host "recipes.${SECRET_DOMAIN}"
              AUTO_BACKUP_ENABLED: true
              ALLOW_SIGNUP: false
              # SMTP_HOST: maddy.comms.svc.cluster.local
              # SMTP_PORT: 2525
              # SMTP_AUTH_STRATEGY: NONE
              # SMTP_FROM_NAME: Recipes
              # SMTP_FROM_EMAIL: "${SMTP_USER}"
              SMTP_HOST: ${SMTP_HOST}
              SMTP_PORT: ${SMTP_PORT}
              SMTP_AUTH_STRATEGY: ${SMTP_AUTH_STRATEGY}
              SMTP_FROM_NAME: Recipes
              SMTP_FROM_EMAIL: "noreply@${SECRET_DOMAIN}"
              LDAP_AUTH_ENABLED: true
              LDAP_SERVER_URL: ${LDAP_URL}
              LDAP_TLS_INSECURE: true
              LDAP_BASE_DN: ${LDAP_BASE_DN}
              LDAP_QUERY_BIND: ${LDAP_READONLY_USER_BIND}
              LDAP_QUERY_PASSWORD: ${LDAP_READONLY_USER_PASSWORD}
              LDAP_USER_FILTER: (memberOf=cn=mealie,ou=groups,dc=home,dc=ld)
              LDAP_ADMIN_FILTER: (memberOf=cn=app-admin,ou=groups,dc=home,dc=ld)
              LDAP_ID_ATTRIBUTE: cn
              LDAP_NAME_ATTRIBUTE: displayName
              LDAP_MAIL_ATTRIBUTE: mail
            envFrom:
              - secretRef:
                  name: mealie-secret
            ports:
              - name: api
                containerPort: 9000
            volumeMounts:
              - name: api-data
                mountPath: /app/data/
    service:
      main:
        ports:
          http:
            port: 3000
      api:
        controller: main
        ports:
          api:
            port: 9000
    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: *host
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      api-data:
        enabled: true
        globalMounts:
          - path: /app/data/
        existingClaim: mealie
