---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paperless-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        PAPERLESS_DBENGINE: postgresql
        PAPERLESS_DBHOST: &dbHost postgres16-rw.database.svc.cluster.local
        PAPERLESS_DBPORT: "5432"
        PAPERLESS_DBUSER: &dbUser "{{ .PAPERLESS__POSTGRES_USER }}"
        PAPERLESS_DBPASS: &dbPass "{{ .PAPERLESS__POSTGRES_PASSWORD }}"
        PAPERLESS_DBNAME: &dbName paperless
        PAPERLESS_ADMIN_USER: "{{ .PAPERLESS__ADMIN_USER }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .PAPERLESS__ADMIN_PASSWORD }}"
        PAPERLESS_SECRET_KEY: "{{ .PAPERLESS__SECRET_KEY }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  data:
    - secretKey: PAPERLESS__ADMIN_USER
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: ce68b3b7-4292-42e2-bbda-b30b99153c99
        property: username
    - secretKey: PAPERLESS__ADMIN_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: ce68b3b7-4292-42e2-bbda-b30b99153c99
        property: password
    - secretKey: PAPERLESS__SECRET_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: ce68b3b7-4292-42e2-bbda-b30b99153c99
        property: secret_key
    - secretKey: PAPERLESS__POSTGRES_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: ce68b3b7-4292-42e2-bbda-b30b99153c99
        property: pg_user
    - secretKey: PAPERLESS__POSTGRES_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: ce68b3b7-4292-42e2-bbda-b30b99153c99
        property: pg_password
    - secretKey: POSTGRES_SUPER_USER
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: username
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: password
