---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-nfs
spec:
  storageClassName: paperless-nfs
  capacity:
    storage: 1Mi # Size does not matter
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: mega.home.ld
    path: /volume1/Media/paperless
  # Note: The first two options are strictly for NFSv4.2
  mountOptions: ["nfsvers=4.0", "nconnect=8", "hard", "noatime"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-nfs
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: paperless-nfs
  resources:
    requests:
      storage: 1Mi # Size does not matter
