---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud-secret
  namespace: selfhosted
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        NEXTCLOUD_USERNAME: "{{ .NEXTCLOUD__USERNAME }}"
        NEXTCLOUD_PASSWORD: "{{ .NEXTCLOUD__PASSWORD }}"
        #REDIS_PASSWORD: "{{ .NEXTCLOUD__REDIS_PASSWORD }}"
        # Database
        POSTGRES_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        POSTGRES_PORT: "5432"
        POSTGRES_DBNAME: &dbName nextcloud
        POSTGRES_USER: &dbUser "{{ .NEXTCLOUD__POSTGRES_USER }}"
        POSTGRES_PASS: &dbPass "{{ .NEXTCLOUD__POSTGRES_PASSWORD }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  data:
    - secretKey: NEXTCLOUD__USERNAME
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: c631e78f-30ab-407f-9fba-736170cad721
        property: username
    - secretKey: NEXTCLOUD__PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: c631e78f-30ab-407f-9fba-736170cad721
        property: password

    #- secretKey: NEXTCLOUD__REDIS_PASSWORD
    #  sourceRef:
    #    storeRef:
    #      name: bitwarden-fields
    #      kind: ClusterSecretStore
    #  remoteRef:
    #    key: c631e78f-30ab-407f-9fba-736170cad721
    #    property: redis_password

    - secretKey: NEXTCLOUD__POSTGRES_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: c631e78f-30ab-407f-9fba-736170cad721
        property: pg_user
    - secretKey: NEXTCLOUD__POSTGRES_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: c631e78f-30ab-407f-9fba-736170cad721
        property: pg_password

    - secretKey: POSTGRES_SUPER_USER
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: username
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: password
