---
# yaml-language-server: $schema=https://kubernetes-schemas.haraldkoch.ca/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: nextcloud-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        NEXTCLOUD_USERNAME: "{{ .NEXTCLOUD_USERNAME }}"
        NEXTCLOUD_PASSWORD: "{{ .NEXTCLOUD_PASSWORD }}"
        POSTGRES_HOST: "{{ .POSTGRES_HOST }}"
        POSTGRES_DBNAME: "{{ .NEXTCLOUD_POSTGRES_DBNAME }}"
        POSTGRES_USER: "{{ .NEXTCLOUD_POSTGRES_USER }}"
        POSTGRES_PASS: "{{ .NEXTCLOUD_POSTGRES_PASS }}"
        # Redis
        REDIS_PASSWORD: "{{ .REDIS_PASSWORD }}"
        # Postgres Init
        INIT_POSTGRES_HOST: "{{ .POSTGRES_HOST }}"
        INIT_POSTGRES_DBNAME: "{{ .NEXTCLOUD_POSTGRES_DBNAME }}"
        INIT_POSTGRES_USER: "{{ .NEXTCLOUD_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .NEXTCLOUD_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # SMTP
        # SMTP_DOMAIN: "{{ .SMTP_DOMAIN }}"
        # SMTP_PORT: "{{ .SMTP_PORT }}"
        # SMTP_SERVER: "{{ .SMTP_SERVER }}"
        # SMTP_USERNAME: "{{ .SMTP_USERNAME }}"
        # SMTP_PASSWORD: "{{ .SMTP_PASSWORD }}"

  dataFrom:
    - extract:
        key: nextcloud
    - extract:
        key: cnpg
    - extract:
        key: redis
    - extract:
        key: smtp-relay
