---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app rook-ceph
  namespace: flux-system
spec:
  targetNamespace: rook-ceph
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/rook-ceph/rook-ceph/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: rook-ceph-operator
      namespace: rook-ceph
  interval: 15m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app rook-ceph-cluster
  namespace: flux-system
spec:
  targetNamespace: rook-ceph
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: rook-ceph
  path: ./kubernetes/apps/rook-ceph/rook-ceph/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  #healthChecks:
  #  - apiVersion: ceph.rook.io/v1
  #    kind: CephCluster
  #    name: ceph-pve-external
  #    namespace: rook-ceph
  wait: false
  interval: 15m
  retryInterval: 1m
  timeout: 5m
