---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: readarr-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        READARR__API_KEY: "{{ .READARR__API_KEY }}"
        READARR__POSTGRES_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        READARR__POSTGRES_PORT: "5432"
        READARR__POSTGRES_USER: &dbUser "{{ .READARR__POSTGRES_USER }}"
        READARR__POSTGRES_PASSWORD: &dbPass "{{ .READARR__POSTGRES_PASSWORD }}"
        READARR__POSTGRES_MAIN_DB: readarr_main
        READARR__POSTGRES_LOG_DB: readarr_log
        READARR__POSTGRES_CACHE_DB: readarr_cache
        # Postgres Init
        INIT_POSTGRES_DBNAME: readarr_main readarr_log readarr_cache
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  data:
    - secretKey: READARR__API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 440a1f9d-5760-4100-97a4-48982fab281a
        property: token
    - secretKey: READARR__POSTGRES_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 440a1f9d-5760-4100-97a4-48982fab281a
        property: pg_user
    - secretKey: READARR__POSTGRES_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 440a1f9d-5760-4100-97a4-48982fab281a
        property: pg_password
    - secretKey: POSTGRES_SUPER_USER
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: username
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: password
