---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app readarr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: longhorn
      namespace: storage
    - name: volsync
      namespace: volsync
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
          secret.reloader.stakater.com/reload: &secret readarr-secret
        #initContainers:
        #  init-db:
        #    image:
        #      repository: ghcr.io/onedr0p/postgres-init
        #      tag: 16
        #      pullPolicy: IfNotPresent
        #    envFrom: &envFrom
        #      - secretRef:
        #          name: readarr-secret
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/readarr-develop
              tag: 0.3.21.2475@sha256:1b661283a46224b4c2266f554c7864f451d7e637336497a0f8503ad869db5e99
            env:
              TZ: ${TIMEZONE}
              READARR__INSTANCE_NAME: Readarr
              READARR__PORT: &port 80
              READARR__LOG_LEVEL: info
            envFrom:
              - secretRef:
                  name: *secret
            resources:
              requests:
                cpu: 15m
                memory: 160M
              limits:
                memory: 330M
        pod:
          securityContext:
            runAsUser: 1031
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: ant-design:read-outlined
          #gethomepage.dev/enabled: "true"
          #gethomepage.dev/group: Downloads
          #gethomepage.dev/name: Readarr
          #gethomepage.dev/icon: readarr.png
          #gethomepage.dev/widget.type: readarr
          #gethomepage.dev/widget.url: http://readarr.downloads
          #gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_READARR_TOKEN}}"
          nginx.ingress.kubernetes.io/configuration-snippet: |-
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.${SECRET_DOMAIN}/css/base/readarr/nord.css"></head>';
            sub_filter_once on;
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: *app
      media:
        type: nfs
        server: mega.home.ld
        path: /volume1/Media
        globalMounts:
          - path: /media
