---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarr-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        SONARR__API_KEY: "{{ .LIDARR__API_KEY }}"
        SONARR__POSTGRES_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        SONARR__POSTGRES_PORT: "5432"
        SONARR__POSTGRES_USER: &dbUser "{{ .LIDARR__POSTGRES_USER }}"
        SONARR__POSTGRES_PASSWORD: &dbPass "{{ .LIDARR__POSTGRES_PASSWORD }}"
        SONARR__POSTGRES_MAIN_DB: lidarr_main
        SONARR__POSTGRES_LOG_DB: lidarr_log
        # Postgres Init
        INIT_POSTGRES_DBNAME: lidarr_main lidarr_log
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # Pushover
        PUSHOVER_TOKEN: "{{ .LIDARR__PUSHOVER_TOKEN }}"
        PUSHOVER_USER_KEY: "{{ .LIDARR__PUSHOVER_USER_KEY }}"
  data:
    - secretKey: LIDARR__API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 1c97df16-2356-4ae4-9186-20bd688c4554
        property: token
    - secretKey: LIDARR__POSTGRES_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 1c97df16-2356-4ae4-9186-20bd688c4554
        property: pg_user
    - secretKey: LIDARR__POSTGRES_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 1c97df16-2356-4ae4-9186-20bd688c4554
        property: pg_password

    - secretKey: POSTGRES_SUPER_USER
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: username
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: password

    - secretKey: LIDARR__PUSHOVER_TOKEN
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 4d219e25-625f-4ac3-838b-4191c9721e9c
        property: username
    - secretKey: LIDARR__PUSHOVER_USER_KEY
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 4d219e25-625f-4ac3-838b-4191c9721e9c
        property: password
