---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wallabag-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        SYMFONY__ENV__DATABASE_DRIVER: pdo_pgsql
        SYMFONY__ENV__DATABASE_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        SYMFONY__ENV__DATABASE_PORT: "5432"
        SYMFONY__ENV__DATABASE_USER: &dbUser "{{ .WALLABAG__POSTGRES_USER }}"
        SYMFONY__ENV__DATABASE_PASSWORD: &dbPass "{{ .WALLABAG__POSTGRES_PASSWORD }}"
        SYMFONY__ENV__DATABASE_NAME: &dbName wallabag
        # Postgres Init
        #INIT_POSTGRES_DBNAME: *dbName
        #INIT_POSTGRES_HOST: *dbHost
        #INIT_POSTGRES_USER: *dbUser
        #INIT_POSTGRES_PASS: *dbPass
        POSTGRES_USER: "{{ .POSTGRES_SUPER_USER }}"
        POSTGRES_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        #INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  data:
    - secretKey: WALLABAG__POSTGRES_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 83abbbe1-25f2-48e4-b862-3af5b7dc5ea8
        property: pg_user
    - secretKey: WALLABAG__POSTGRES_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 83abbbe1-25f2-48e4-b862-3af5b7dc5ea8
        property: pg_password
    - secretKey: POSTGRES_SUPER_USER
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: username
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: password
