---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gatus-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        DISCORD_WEBHOOK_URL: "{{ .DISCORD_WEBHOOK_URL }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: gatus
        INIT_POSTGRES_HOST: postgres-lb.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  data:
    - secretKey: DISCORD_WEBHOOK_URL
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: a3225ace-b57a-406e-b3d7-e1b123e18a98
        property: discord_webhook
    - secretKey: POSTGRES_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: a3225ace-b57a-406e-b3d7-e1b123e18a98
        property: pg_user
    - secretKey: POSTGRES_PASS
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: a3225ace-b57a-406e-b3d7-e1b123e18a98
        property: pg_password
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: password
