---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lldap-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        LLDAP_JWT_SECRET: "{{ .LLDAP__JWT_SECRET }}"
        LLDAP_LDAP_USER_PASS: "{{ .LLDAP__LDAP_USER_PASS }}"
        LLDAP_USER_DN: "{{ .LLDAP__USER_DN }}"
        LLDAP_LDAP_USER_EMAIL: "{{ .LLDAP__LDAP_USER_EMAIL }}"
        LLDAP_SERVER_KEY_SEED: "{{ .LLDAP__SERVER_KEY_SEED }}"
        # Database
        LLDAP_POSTGRES_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        LLDAP_POSTGRES_PORT: "5432"
        LLDAP_POSTGRES_USER: &dbUser "{{ .LLDAP__POSTGRES_USER }}"
        LLDAP_POSTGRES_PASSWORD: &dbPass "{{ .LLDAP__POSTGRES_PASSWORD }}"
        LLDAP_POSTGRES_DB: &dbName lldap
        LLDAP_DATABASE_URL: |-
          postgres://{{ .LLDAP_POSTGRES_USER }}:{{ .LLDAP_POSTGRES_PASS }}@{{ .LLDAP_POSTGRES_HOST }}/{{ .LLDAP_POSTGRES_DB }}
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  data:
    - secretKey: LLDAP__POSTGRES_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: c9de4f31-9d8c-4169-b6ca-ec4b585acad8
        property: pg_user
    - secretKey: LLDAP__POSTGRES_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: c9de4f31-9d8c-4169-b6ca-ec4b585acad8
        property: pg_password
    - secretKey: LLDAP__JWT_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: c9de4f31-9d8c-4169-b6ca-ec4b585acad8
        property: token

    - secretKey: LLDAP__USER_DN
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: c9de4f31-9d8c-4169-b6ca-ec4b585acad8
        property: username
    - secretKey: LLDAP__USER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: c9de4f31-9d8c-4169-b6ca-ec4b585acad8
        property: password

    - secretKey: POSTGRES_SUPER_USER
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: username
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b9279f83-6c73-4cbc-9949-3c820f267c58
        property: password
