---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: friendica-secret
  namespace: selfhosted
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        db_host: mariadb-galera-primary.database.svc.cluster.local
        db_user: "{{ .FRIENDICA__DB_USER }}"
        db_pass: "{{ .FRIENDICA__DB_PASS }}"
        db_name: friendica
        admin_email: "{{ .FRIENDICA__ADMIN_EMAIL }}"
        redis_password: "{{ .REDIS__PASSWORD }}"
  data:
    - secretKey: FRIENDICA__DB_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 0e5d8714-665f-4de5-a759-e73b86f52c16
        property: mariadb_user
    - secretKey: FRIENDICA__DB_PASS
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 0e5d8714-665f-4de5-a759-e73b86f52c16
        property: mariadb_password

    - secretKey: FRIENDICA__ADMIN_EMAIL
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 0e5d8714-665f-4de5-a759-e73b86f52c16
        property: username

    - secretKey: REDIS_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 13f695cc-7beb-410a-bc1b-abc7480b371a
        property: redis_password
