---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: privatebin
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.3.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      main:
        type: statefulset

        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          enableServiceLinks: false

        statefulset:
          volumeClaimTemplates:
            - name: data
              accessMode: ReadWriteMany
              size: 5Gi
              storageClass: cephfs
              globalMounts:
                - path: /srv/data

        containers:
          main:
            image:
              repository: ghcr.io/privatebin/nginx-fpm-alpine
              tag: stable
            env:
              TZ: America/Toronto
              PHP_TZ: America/Toronto
            resources:
              requests:
                cpu: 12m
                memory: 256M
              limits:
                memory: 512M

    service:
      main:
        ports:
          http:
            port: 8080

    ingress:
      main:
        enabled: true
        className: "internal"
        hosts:
          - host: &host "{{ .Release.Name }}.deckersheaven.com"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host